/**
 * SENTINEL — Deutsche Übersetzungen aller Scan-Check-Beschreibungen
 * German translations for all scan check detail templates.
 * Used by mergeCheckDetails.ts when language is 'de'.
 */

import type { CheckDetailTemplate } from './networkScanChecks';

// ═══════════════════════════════════════════════════════════════
// NETZWERK — 15 Prüfungen
// ═══════════════════════════════════════════════════════════════

export const NETWORK_CHECK_DETAILS_DE: Record<string, CheckDetailTemplate> = {
  'wfp-kernel-filter': {
    whatChecked: 'Windows-Filterplattform-Kerneltreiber, Basisfilter-Engine (BFE) und Windows-Firewall-Dienst (MpsSvc).',
    riskExplanation: 'WFP ist der Paketfilter auf Kernelebene. Wenn BFE oder MpsSvc stoppt, werden ALLE Firewall-Regeln stillschweigend deaktiviert — Ihr Rechner ist vollständig exponiert.',
    passDetail: 'BFE-Dienst läuft. MpsSvc-Dienst läuft. WFP-Kerneltreiber geladen.',
    fixActionsTemplate: ['BFE-Dienst starten (sc start BFE)', 'MpsSvc-Dienst starten', 'WFP-Treiber neu laden'],
    preserves: ['Bestehende Firewall-Regeln', 'Netzwerkverbindungen'],
    canUndo: false,
  },
  'tcp-stack-hardening': {
    whatChecked: 'SynAttackProtect, DeadGWRetryCount, KeepAliveTime und IP-Source-Routing-Registrierungseinstellungen.',
    riskExplanation: 'Schwache TCP-Stack-Einstellungen ermöglichen SYN-Flood-Angriffe, Dead-Gateway-Exploits und Source-Routing-Hijacks.',
    passDetail: 'SynAttackProtect aktiviert. DeadGW-Wiederholungen reduziert. Source-Routing deaktiviert.',
    fixActionsTemplate: ['SynAttackProtect=1 setzen', 'DeadGWRetryCount auf 1 reduzieren', 'IP-Source-Routing deaktivieren', 'TCP/IP-Stack neu starten'],
    preserves: ['Aktive Verbindungen werden nicht unterbrochen', 'Firewall-Regeln bleiben unverändert'],
    canUndo: true,
    undoPath: 'Registry → TCP/IP Parameters → Standardwerte wiederherstellen',
  },
  'port-stealthing': {
    whatChecked: 'ICMP-Echo-Antwort, häufige Scan-Ports (135, 139, 445, 3389) Sichtbarkeit für externe Scanner.',
    riskExplanation: 'Antwortende ICMP-Echos und offene Probe-Ports machen Ihren Rechner für automatisierte Scanner und Wurm-Verbreitung sichtbar.',
    passDetail: 'ICMP-Echo blockiert. Häufige Probe-Ports getarnt oder gefiltert.',
    fixActionsTemplate: ['ICMP-Echo-Antwort ausgehend blockieren', 'Stealth-Regeln für Ports 135, 139, 445, 3389 erstellen'],
    preserves: ['LAN-Dateifreigabe falls konfiguriert', 'RDP falls explizit erlaubt'],
    canUndo: true,
    undoPath: 'Firewall → Rückgängig',
  },
  'beaconing-detection': {
    whatChecked: 'Ausgehende Verbindungen mit regelmäßigen Zeitintervallen (potenzielle C2-Beacon-Muster).',
    riskExplanation: 'Command-&-Control-Beacons können Daten exfiltrieren, Malware-Payloads herunterladen oder dauerhaften Zugriff aufrechterhalten.',
    passDetail: 'Keine Prozesse zeigen verdächtige periodische Verbindungsmuster.',
    fixActionsTemplate: ['Top-Beaconing-IPs in der Firewall blockieren', 'Markierte IPs zur Watchlist hinzufügen', 'Blockierte Verbindungen in Threat-Timeline protokollieren'],
    preserves: ['Browser-Verbindungen zu sicheren Domains', 'Bestehende Firewall-Regeln'],
    canUndo: true,
    undoPath: 'Firewall → Rückgängig',
  },
  'app-layer-gateway': {
    whatChecked: 'Application Layer Gateway (ALG) Dienststatus für FTP-, SIP-, PPTP-Protokollbehandlung.',
    riskExplanation: 'ALG fängt Netzwerkverkehr auf Anwendungsebene ab und modifiziert ihn. Bei Ausnutzung können Angreifer Firewall-Regeln vollständig umgehen.',
    passDetail: 'ALG-Dienst gestoppt oder auf notwendige Protokolle beschränkt.',
    fixActionsTemplate: ['ALG-Dienst deaktivieren (sc stop ALG)', 'Auf benötigte Protokolle beschränken'],
    preserves: ['FTP-Verbindungen benötigen ggf. manuelle Portweiterleitung', 'SIP/VoIP falls in Verwendung'],
    canUndo: true,
    undoPath: 'Dienste → ALG → Auf Automatisch setzen',
  },
  'geo-ip-blocking': {
    whatChecked: 'Vorhandensein von ein-/ausgehenden Firewall-Regeln für bekannte Hochrisiko-Länder-IP-Bereiche.',
    riskExplanation: 'Ohne Geo-Blocking erreicht Datenverkehr aus feindlichen Regionen Ihren Rechner uneingeschränkt. Viele automatisierte Angriffe stammen aus bestimmten Ländern.',
    passDetail: 'Geo-Block-Regeln für Hochrisiko-Regionen aktiv.',
    fixActionsTemplate: ['Ausgehende Blockregeln für Hochrisiko-IP-Bereiche erstellen', 'Ausnahmeregeln für legitime Dienste hinzufügen', 'IP-Bereichsdatenbank aktualisieren'],
    preserves: ['Verbindungen zu großen Cloud-Diensten (AWS, Azure, GCP)', 'VPN-Verkehr unberührt'],
    canUndo: true,
    undoPath: 'Firewall → Rückgängig → Geo-Block-Regeln entfernen',
  },
  'process-outbound-control': {
    whatChecked: 'Ob ausgehende Verbindungen pro Prozess gefiltert oder global erlaubt werden (Standard: Erlauben).',
    riskExplanation: 'Standard-Erlauben für ausgehend lässt JEDEN Prozess zu JEDEM Server verbinden. Malware, Spyware und Datenexfiltrations-Tools arbeiten uneingeschränkt.',
    passDetail: 'Ausgehendes Firewall-Profil mit prozessbasierten Regeln konfiguriert. Standard ausgehend: Blockieren.',
    fixActionsTemplate: ['Ausgehenden Standard auf Blockieren setzen', 'Erlauben-Regeln für bekannte Programme erstellen', 'Blockierte Versuche im Ereignisprotokoll überwachen'],
    preserves: ['Bestehende Erlauben-Regeln bleiben aktiv', 'Browser und Systemupdates funktionieren weiter'],
    canUndo: true,
    undoPath: 'Firewall → Ausgehende Richtlinie → Standard Erlauben setzen',
  },
  'arp-table-status': {
    whatChecked: 'ARP-Tabelle auf doppelte MACs, statische vs. dynamische Einträge und potenzielle ARP-Spoofing-Indikatoren.',
    riskExplanation: 'ARP-Spoofing ermöglicht Angreifern in Ihrem LAN, Ihren gesamten Datenverkehr abzufangen (Man-in-the-Middle). Rein dynamische ARP-Tabellen sind anfällig.',
    passDetail: 'ARP-Tabelle sauber. Keine doppelten MACs. Gateway hat statischen Eintrag.',
    fixActionsTemplate: ['Gateway-MAC als statischen ARP-Eintrag setzen', 'Dynamic ARP Inspection aktivieren falls Switch es unterstützt'],
    preserves: ['Netzwerkkonnektivität unverändert', 'DHCP funktioniert weiter'],
    canUndo: true,
    undoPath: 'ARP → Statischen Eintrag löschen',
  },
  'dns-over-https': {
    whatChecked: 'Ob DNS-Abfragen verschlüsselten Transport (DoH/DoT) oder Klartext-UDP/53 verwenden.',
    riskExplanation: 'Klartext-DNS legt jede besuchte Domain für jeden in Ihrem Netzwerk, Ihren ISP und potenzielle Lauscher offen.',
    passDetail: 'DNS-Abfragen über verschlüsseltes DNS (DoH oder VPN-Tunnel) geleitet.',
    fixActionsTemplate: ['DoH in Windows-DNS-Einstellungen aktivieren', 'DoH-Server konfigurieren (z.B. Cloudflare 1.1.1.1)', 'Klartext-DNS (Port 53) in Firewall blockieren'],
    preserves: ['VPN-DNS-Routing falls aktiv', 'Lokale Netzwerk-DNS-Auflösung'],
    canUndo: true,
    undoPath: 'DNS & Datenschutz → DNS-Konfiguration → Wiederherstellen',
  },
  'tor-proxy-blocking': {
    whatChecked: 'Ob bekannte Tor-Exit-Node-IPs und SOCKS-Proxy-Ports blockiert sind.',
    riskExplanation: 'Offener Tor/Proxy-Zugang ermöglicht Malware, ihren Datenverkehr zu anonymisieren und Geo-Beschränkungen auf C2-Servern zu umgehen.',
    passDetail: 'Bekannte Tor-Exit-Nodes blockiert. SOCKS-Proxy-Ports eingeschränkt.',
    fixActionsTemplate: ['Bekannte Tor-Exit-Node-IP-Bereiche blockieren', 'SOCKS-Ports 1080, 9050, 9150 einschränken'],
    preserves: ['Legitime VPN-Verbindungen', 'Browser-Proxy-Einstellungen falls konfiguriert'],
    canUndo: true,
    undoPath: 'Firewall → Rückgängig',
  },
  'domain-reputation-filter': {
    whatChecked: 'Ob DNS-Abfragen zu bekannten bösartigen Domains über Hosts-Datei oder DNS-Filter blockiert werden.',
    riskExplanation: 'Ohne Domain-Filterung werden Phishing-, Malware-Verteilungs- und Ad-Tracking-Domains normal aufgelöst. Dies ist der häufigste Angriffsvektor für browserbasierte Angriffe.',
    passDetail: 'Domain-Reputationsfilter aktiv. Blockliste mit bekannten bösartigen Domains geladen.',
    fixActionsTemplate: ['Hosts-Datei mit bösartiger Domain-Blockliste aktualisieren', 'DNS-Level-Filterung aktivieren', 'Überwachung für blockierte Abfragen hinzufügen'],
    preserves: ['Zugriff auf legitime Websites', 'Bestehende Hosts-Datei-Einträge'],
    canUndo: true,
    undoPath: 'DNS & Datenschutz → Hosts-Datei → Backup wiederherstellen',
  },
  'zero-trust-isolation': {
    whatChecked: 'Netzwerkprofil (Öffentlich/Privat/Domäne), Firewall-Regeln für eingehende Standards und Netzwerkerkennung.',
    riskExplanation: 'Nicht-öffentliche Netzwerkprofile aktivieren Dateifreigabe, Druckerfreigabe und Netzwerkerkennung — und exponieren Dienste für nahegelegene Angreifer.',
    passDetail: 'Netzwerkprofil: Öffentlich. Eingehender Standard: Blockieren. Netzwerkerkennung: Deaktiviert.',
    fixActionsTemplate: ['Netzwerkprofil auf Öffentlich für nicht vertrauenswürdige Netzwerke setzen', 'Netzwerkerkennung deaktivieren', 'Eingehend standardmäßig blockieren'],
    preserves: ['Ausgehende Verbindungen unverändert', 'VPN-Verkehr unberührt'],
    canUndo: true,
    undoPath: 'Netzwerkeinstellungen → Profil zurück auf Privat ändern',
  },
  'dpi-tls-check': {
    whatChecked: 'TLS-Versionen in aktiven Verbindungen. Prüfung auf veraltete TLS 1.0/1.1.',
    riskExplanation: 'TLS 1.0 und 1.1 haben bekannte Schwachstellen. Verbindungen mit diesen Protokollen können abgefangen oder herabgestuft werden.',
    passDetail: 'Alle aktiven TLS-Verbindungen verwenden TLS 1.2 oder 1.3.',
    fixActionsTemplate: ['TLS 1.0 und 1.1 in der Windows-Registry deaktivieren', 'SChannel-Einstellungen aktualisieren'],
    preserves: ['TLS 1.2- und 1.3-Verbindungen', 'HTTPS-Browsing'],
    canUndo: true,
    undoPath: 'Registry → SChannel → TLS 1.0/1.1 wieder aktivieren',
  },
  'smb-kill-switch': {
    whatChecked: 'SMBv1-Protokollstatus, SMB-Signierung und SMB-Verschlüsselungseinstellungen.',
    riskExplanation: 'SMBv1 ist das von WannaCry und EternalBlue ausgenutzte Protokoll. Es muss auf jedem modernen System deaktiviert sein.',
    passDetail: 'SMBv1 deaktiviert. SMBv2/v3 mit Signierung aktiviert.',
    fixActionsTemplate: ['SMBv1-Client und -Server deaktivieren', 'SMB-Signierung aktivieren', 'SMB-Verschlüsselung aktivieren'],
    preserves: ['SMBv2/v3-Dateifreigabe funktioniert weiter', 'Druckerfreigabe bei Verwendung von SMBv2+'],
    canUndo: true,
    undoPath: 'Windows-Features → SMBv1 wieder aktivieren',
  },
  'netflow-active-connections': {
    whatChecked: 'Anzahl aktiver Verbindungen, lauschende Ports und Verbindungswechselrate.',
    riskExplanation: 'Ungewöhnliche Verbindungszahlen oder hohe Wechselraten können auf Malware-Aktivität, Port-Scanning oder Datenexfiltration hinweisen.',
    passDetail: 'Verbindungszahlen im normalen Bereich. Keine auffälligen Listener erkannt.',
    fixActionsTemplate: ['Verdächtige lauschende Ports schließen', 'Prozesse mit hoher Wechselrate blockieren', 'Zur Überwachungs-Watchlist hinzufügen'],
    preserves: ['Aktive Browser-Sitzungen', 'System-Dienstverbindungen'],
    canUndo: true,
    undoPath: 'Firewall → Rückgängig',
  },
};

// ═══════════════════════════════════════════════════════════════
// DATENSCHUTZ — 22 Prüfungen
// ═══════════════════════════════════════════════════════════════

export const PRIVACY_CHECK_DETAILS_DE: Record<string, CheckDetailTemplate> = {
  'hardware-id-exposure': {
    whatChecked: 'Zugriff auf die Windows-Hardware-ID (UUID) durch Anwendungen und Websites.',
    riskExplanation: 'Hardware-IDs identifizieren Ihren Rechner eindeutig. Bei Offenlegung können Tracker Sie über Browser-Sitzungen, VPNs und Kontowechsel hinweg verfolgen.',
    passDetail: 'Hardware-ID-Zugriff eingeschränkt.',
    fixActionsTemplate: ['WMIC-Zugriff auf Administratoren beschränken', 'Hardware-ID-Abfragen von Nicht-Admin-Prozessen blockieren'],
    preserves: ['Systemfunktionalität', 'Treiberinstallationen'],
    canUndo: true,
    undoPath: 'Einstellungen → Datenschutz → Hardware-ID-Zugriff wiederherstellen',
  },
  'advertising-id': {
    whatChecked: 'Windows-Werbe-ID-Status (wird von Microsoft und Drittanbieter-Apps für Anzeigen-Targeting verwendet).',
    riskExplanation: 'Die Werbe-ID ermöglicht Apps und Werbetreibenden, Ihr Verhalten über alle Microsoft-Store-Apps hinweg zu verfolgen.',
    passDetail: 'Werbe-ID deaktiviert.',
    fixActionsTemplate: ['Werbe-ID über Registry deaktivieren', 'Werbe-ID zurücksetzen'],
    preserves: ['App-Funktionalität', 'Microsoft-Store-Zugang'],
    canUndo: true,
    undoPath: 'Windows-Einstellungen → Datenschutz → Werbe-ID → Ein',
  },
  'telemetry-registry': {
    whatChecked: 'Windows-Telemetriestufe, DiagTrack-Dienst und Connected-User-Experiences-Dienst.',
    riskExplanation: 'Volle Telemetrie sendet detaillierte Nutzungsdaten, App-Absturzberichte und Browsing-Daten an Microsoft. Selbst die Stufe „Erforderlich" sendet erhebliche Daten.',
    passDetail: 'Telemetrie auf Minimum gesetzt. DiagTrack-Dienst eingeschränkt.',
    fixActionsTemplate: ['Telemetrie auf Erforderlich (0) setzen', 'DiagTrack-Dienst deaktivieren', 'Telemetrie-Endpunkte in Hosts-Datei blockieren'],
    preserves: ['Windows-Update-Funktionalität', 'Microsoft-Defender-Updates'],
    canUndo: true,
    undoPath: 'Windows-Einstellungen → Datenschutz → Diagnose → Vollständig',
  },
  'webcam-mic-lock': {
    whatChecked: 'Kamera- und Mikrofonzugriffsberechtigungen, welche Apps Zugriff haben, und Benachrichtigungseinstellungen.',
    riskExplanation: 'Uneingeschränkter Webcam-/Mikrofon-Zugriff ermöglicht Spyware, Audio/Video ohne sichtbare Indikatoren aufzuzeichnen.',
    passDetail: 'Kamera und Mikrofon erfordern App-Einzelzustimmung. Zugriffsbenachrichtigungen aktiviert.',
    fixActionsTemplate: ['Globalen Kamerazugriff deaktivieren', 'Globalen Mikrofonzugriff deaktivieren', 'Zugriffsbenachrichtigungen aktivieren'],
    preserves: ['Kamera/Mikrofon funktionieren wenn Sie sie explizit erlauben'],
    canUndo: true,
    undoPath: 'Windows-Einstellungen → Datenschutz → Kamera/Mikrofon → Ein',
  },
  'clipboard-history': {
    whatChecked: 'Zwischenablage-Verlauf, geräteübergreifende Synchronisierung und Datenaufbewahrung.',
    riskExplanation: 'Der Zwischenablage-Verlauf speichert alles, was Sie kopieren — Passwörter, sensiblen Text, private Daten — und synchronisiert möglicherweise in die Cloud.',
    passDetail: 'Zwischenablage-Verlauf deaktiviert. Cloud-Synchronisierung aus.',
    fixActionsTemplate: ['Zwischenablage-Verlauf deaktivieren', 'Cloud-Synchronisierung der Zwischenablage deaktivieren', 'Zwischenablage-Daten löschen'],
    preserves: ['Normales Kopieren/Einfügen funktioniert weiter', 'Nur kein Verlauf gespeichert'],
    canUndo: true,
    undoPath: 'Windows-Einstellungen → System → Zwischenablage → Verlauf Ein',
  },
  'metadata-stripper': {
    whatChecked: 'Ob Sentinel-Metadaten-Bereinigung für extern freigegebene Dateien verfügbar ist.',
    riskExplanation: 'Fotos und Dokumente enthalten versteckte Metadaten: GPS-Standort, Geräteinformationen, Autorname, Bearbeitungsverlauf. Teilen ohne Bereinigung gibt persönliche Daten preis.',
    passDetail: 'Metadaten-Bereinigung über Vault verfügbar.',
    fixActionsTemplate: ['Automatische Metadaten-Bereinigung für Uploads aktivieren'],
    preserves: ['Originaldateien unberührt', 'Bereinigte Kopien werden erstellt'],
    canUndo: false,
  },
  'cortana-web-search': {
    whatChecked: 'Cortana-Status, Websuche aus dem Startmenü und Bing-Integration in der Windows-Suche.',
    riskExplanation: 'Die Startmenü-Websuche sendet jede Suchanfrage an Microsoft/Bing, einschließlich Tippfehler und sensibler Suchanfragen.',
    passDetail: 'Cortana deaktiviert. Websuche aus dem Startmenü deaktiviert.',
    fixActionsTemplate: ['Cortana über Registry deaktivieren', 'BingSearchEnabled deaktivieren', 'Webergebnisse im Startmenü deaktivieren'],
    preserves: ['Lokale Dateisuche funktioniert weiter', 'Einstellungssuche funktioniert'],
    canUndo: true,
    undoPath: 'Registry → Search → BingSearchEnabled=1',
  },
  'error-reporting': {
    whatChecked: 'Windows-Fehlerberichterstattung (WER) Dienst und Absturzbericht-Upload-Einstellungen.',
    riskExplanation: 'Fehlerberichte können Speicherabbilder mit Passwörtern, Sitzungstoken und privaten Daten enthalten. Diese werden an Microsoft hochgeladen.',
    passDetail: 'WER-Dienst gestoppt. Absturzberichte werden nur lokal gespeichert.',
    fixActionsTemplate: ['WerSvc-Dienst stoppen', 'WER auf Nur-Lokal-Modus setzen', 'Automatische Absturzbericht-Uploads deaktivieren'],
    preserves: ['Lokale Absturzberichte werden weiterhin für Fehlersuche erstellt'],
    canUndo: true,
    undoPath: 'Dienste → WerSvc → Automatisch',
  },
  'wifi-sense': {
    whatChecked: 'WiFi Sense, automatische Hotspot-Verbindung und offene Netzwerkfreigabe.',
    riskExplanation: 'WiFi Sense teilt Ihre WLAN-Passwörter mit Kontakten und verbindet sich automatisch mit offenen Netzwerken — beides erhebliche Sicherheitsrisiken.',
    passDetail: 'WiFi Sense deaktiviert. Automatische Verbindung mit offenen Netzwerken aus.',
    fixActionsTemplate: ['WiFi Sense deaktivieren', 'Automatische Verbindung mit empfohlenen offenen Hotspots deaktivieren'],
    preserves: ['Manuelle WLAN-Verbindungen funktionieren normal'],
    canUndo: true,
    undoPath: 'Netzwerkeinstellungen → WLAN → Erweitert → WiFi Sense aktivieren',
  },
  'bluetooth-status': {
    whatChecked: 'Bluetooth-Adapter-Status, Sichtbarkeit und Kopplungsmodus.',
    riskExplanation: 'Ständig aktives Bluetooth im Erkennungsmodus ermöglicht nahegelegenen Angreifern, Ihr Gerät zu scannen, Kopplungsversuche durchzuführen und BT-Schwachstellen auszunutzen.',
    passDetail: 'Bluetooth läuft, aber nicht im Erkennungsmodus.',
    fixActionsTemplate: ['Bluetooth deaktivieren wenn nicht in Verwendung', 'Auf nicht erkennbar setzen'],
    preserves: ['Gekoppelte Geräte funktionieren weiter'],
    canUndo: true,
    undoPath: 'Bluetooth-Einstellungen → Einschalten / Erkennbar machen',
  },
  'gpo-hardening': {
    whatChecked: 'Gruppenrichtlinien-Einstellungen für Sicherheit: Überwachungsrichtlinien, Kontosperrung, Bildschirmsperre.',
    riskExplanation: 'Ohne gehärtete GPOs fehlt die Kontosperrung (Brute-Force funktioniert unbegrenzt), Audit-Logging ist deaktiviert und Autorun ist aktiviert.',
    passDetail: 'GPO-Härtung aktiv. Kontosperrung konfiguriert. Audit-Richtlinien gesetzt.',
    fixActionsTemplate: ['Kontosperrungsrichtlinie konfigurieren', 'Sicherheits-Audit-Richtlinien aktivieren', 'Autorun deaktivieren'],
    preserves: ['Normale Anmeldung', 'Gruppenrichtlinien-Verwaltung'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinien → Standardwerte wiederherstellen',
  },
  'uac-stealth-mode': {
    whatChecked: 'UAC-Stufe, Secure-Desktop-Einstellung und Admin-Genehmigungsmodus.',
    riskExplanation: 'Herabgesetzte UAC ermöglicht Schadsoftware, sich ohne Benutzerinteraktion auf Administratorebene zu erheben.',
    passDetail: 'UAC auf maximaler Stufe. Secure Desktop aktiviert.',
    fixActionsTemplate: ['UAC auf „Immer benachrichtigen" setzen', 'Secure Desktop aktivieren', 'Admin-Genehmigungsmodus aktivieren'],
    preserves: ['Normale Programmausführung', 'Administratorfunktionen'],
    canUndo: true,
    undoPath: 'UAC-Einstellungen → Vorherige Stufe wiederherstellen',
  },
  'military-shredder': {
    whatChecked: 'Ob die sichere Dateilöschung (militärischer Standard) über Sentinel Vault verfügbar ist.',
    riskExplanation: 'Normales Löschen entfernt nur den Verzeichniseintrag. Dateien sind mit Wiederherstellungstools vollständig lesbar.',
    passDetail: 'Sichere Dateilöschung über Vault verfügbar.',
    fixActionsTemplate: ['Dateien über Vault sicher schreddern'],
    preserves: ['Andere Dateien im selben Verzeichnis'],
    canUndo: false,
  },
  'anti-keylogging': {
    whatChecked: 'Schutz gegen Keylogger: Tastatur-Hook-Erkennung und Input-Verschleierung.',
    riskExplanation: 'Keylogger zeichnen jeden Tastendruck auf — Passwörter, Nachrichten, Suchbegriffe. Ohne Schutz ist jede Eingabe kompromittiert.',
    passDetail: 'Anti-Keylogging-Schutz aktiv.',
    fixActionsTemplate: ['Tastatur-Hook-Überwachung aktivieren', 'Verdächtige Hooks melden'],
    preserves: ['Normale Tastatureingabe', 'Barrierefreiheits-Software'],
    canUndo: true,
    undoPath: 'Einstellungen → Datenschutz → Anti-Keylogging deaktivieren',
  },
  'tracking-protection': {
    whatChecked: 'Browser-Fingerprinting-Schutz, Canvas-Fingerprint-Blockierung und WebRTC-IP-Leak-Prävention.',
    riskExplanation: 'Browser-Fingerprinting identifiziert Benutzer ohne Cookies durch Hardware- und Software-Merkmale. WebRTC kann echte IPs trotz VPN preisgeben.',
    passDetail: 'Tracking-Schutz aktiv. WebRTC-Leak-Schutz aktiviert.',
    fixActionsTemplate: ['WebRTC-IP-Leak blockieren', 'Canvas-Fingerprinting-Schutz aktivieren'],
    preserves: ['Normale Web-Browsing-Funktionalität', 'Video-Anrufe (WebRTC für erlaubte Seiten)'],
    canUndo: true,
    undoPath: 'Einstellungen → Datenschutz → Tracking-Schutz deaktivieren',
  },
  'dns-leak-protection': {
    whatChecked: 'Ob DNS-Abfragen bei aktiver VPN-Verbindung durch den VPN-Tunnel geleitet werden.',
    riskExplanation: 'DNS-Leaks verraten besuchte Websites trotz VPN an den ISP. Der VPN-Schutz wird damit nutzlos.',
    passDetail: 'DNS-Leak-Schutz aktiv. Alle Abfragen über VPN-Tunnel.',
    fixActionsTemplate: ['DNS-Leak-Schutz in VPN-Einstellungen aktivieren', 'DNS-Server auf VPN-DNS setzen'],
    preserves: ['VPN-Verbindung', 'DNS-Auflösung'],
    canUndo: true,
    undoPath: 'VPN-Einstellungen → DNS-Leak-Schutz deaktivieren',
  },
  'location-services': {
    whatChecked: 'Windows-Standortdienste, App-Zugriff auf Standortdaten und Standortverlauf.',
    riskExplanation: 'Aktivierte Standortdienste ermöglichen Apps, Ihren physischen Standort zu verfolgen. Der Standortverlauf speichert Bewegungsprofile.',
    passDetail: 'Standortdienste eingeschränkt. Standortverlauf deaktiviert.',
    fixActionsTemplate: ['Standortdienste für nicht benötigte Apps deaktivieren', 'Standortverlauf löschen und deaktivieren'],
    preserves: ['Standortdienste für explizit erlaubte Apps', 'Wetteranzeige falls gewünscht'],
    canUndo: true,
    undoPath: 'Windows-Einstellungen → Datenschutz → Standort → Ein',
  },
  'winget-available': {
    whatChecked: 'Ob Windows Package Manager (winget) für sichere Software-Installation verfügbar ist.',
    riskExplanation: 'Ohne verifizierten Paketmanager laden Benutzer Software von unbekannten Quellen herunter — ein häufiger Malware-Infektionsweg.',
    passDetail: 'Winget verfügbar und funktionsfähig.',
    fixActionsTemplate: ['Winget über Microsoft Store installieren', 'App Installer aktualisieren'],
    preserves: ['Bestehende Software', 'Manuelle Installation weiterhin möglich'],
    canUndo: false,
  },
  'usb-storage': {
    whatChecked: 'USB-Massenspeicher-Richtlinie, AutoRun für Wechseldatenträger und Gerätebeschränkungen.',
    riskExplanation: 'Uneingeschränkter USB-Zugang ermöglicht Datendiebstahl über physischen Zugriff und Malware-Infektion über infizierte USB-Geräte (BadUSB).',
    passDetail: 'USB-Massenspeicher eingeschränkt oder überwacht.',
    fixActionsTemplate: ['USB-Massenspeicher-Zugriff einschränken', 'AutoRun für Wechseldatenträger deaktivieren'],
    preserves: ['USB-Tastaturen und -Mäuse', 'USB-Drucker'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinien → Wechseldatenträger → Zugriff erlauben',
  },
  'lockscreen-hardening': {
    whatChecked: 'Sperrbildschirm-Timeout, Benachrichtigungsanzeige und Informationsoffenlegung.',
    riskExplanation: 'Ohne Sperrbildschirm-Härtung zeigt Windows Benachrichtigungsinhalte, E-Mails und Nachrichten auf dem Sperrbildschirm — für jeden sichtbar.',
    passDetail: 'Sperrbildschirm gehärtet. Benachrichtigungsinhalte ausgeblendet.',
    fixActionsTemplate: ['Benachrichtigungsinhalte auf Sperrbildschirm ausblenden', 'Timeout auf 5 Minuten setzen'],
    preserves: ['Sperrbildschirmfunktionalität', 'Benachrichtigungen nach Entsperren sichtbar'],
    canUndo: true,
    undoPath: 'Einstellungen → System → Benachrichtigungen → Auf Sperrbildschirm anzeigen',
  },
  'shell-extension-audit': {
    whatChecked: 'Installierte Shell-Erweiterungen, Kontextmenü-Handler und Browser-Helper-Objekte.',
    riskExplanation: 'Bösartige Shell-Erweiterungen laden bei jedem Rechtsklick Code in den Explorer-Prozess und können Dateizugriffe überwachen.',
    passDetail: 'Alle Shell-Erweiterungen von verifizierten Herausgebern.',
    fixActionsTemplate: ['Unbekannte Shell-Erweiterungen deaktivieren', 'Kontextmenü-Handler prüfen'],
    preserves: ['Windows-Explorer-Funktionalität', 'Verifizierte Erweiterungen'],
    canUndo: true,
    undoPath: 'Shell-Erweiterungen über Registry wieder aktivieren',
  },
  'data-science-dashboard': {
    whatChecked: 'Ob Sentinel Datenschutz-Dashboard mit Übersicht aller Schutzmaßnahmen verfügbar ist.',
    riskExplanation: 'Ohne zentrale Übersicht ist der Datenschutzstatus unklar und Lücken bleiben unbemerkt.',
    passDetail: 'Datenschutz-Dashboard aktiv und vollständig.',
    fixActionsTemplate: ['Datenschutz-Dashboard in Einstellungen prüfen'],
    preserves: ['Alle bestehenden Einstellungen'],
    canUndo: false,
  },
};
