/**
 * SENTINEL — Deutsche EDR-Scan-Check-Beschreibungen (24 Prüfungen)
 */
import type { CheckDetailTemplate } from './networkScanChecks';

export const EDR_CHECK_DETAILS_DE: Record<string, CheckDetailTemplate> = {
  'amsi-status': {
    whatChecked: 'Antimalware Scan Interface (AMSI) Anbieterregistrierung und Bypass-Erkennung.',
    riskExplanation: 'AMSI ist die erste Verteidigungslinie gegen dateilose Malware. Bei Umgehung oder Deaktivierung werden PowerShell- und VBScript-Angriffe unerkannt ausgeführt.',
    passDetail: 'AMSI-Anbieter registriert und aktiv. Keine Bypass-Indikatoren erkannt.',
    fixActionsTemplate: ['AMSI-Anbieter-DLL neu registrieren', 'Auf AMSI-Bypass-Patches im Speicher prüfen', 'AMSI-Logging aktivieren'],
    preserves: ['PowerShell-Funktionalität', 'Skript-Ausführung unverändert'],
    canUndo: false,
  },
  'etw-integrity': {
    whatChecked: 'Event Tracing for Windows (ETW) Anbieterstatus und Manipulationsindikatoren.',
    riskExplanation: 'ETW protokolliert Sicherheitsereignisse in Windows. Fortgeschrittene Malware patcht ETW, um ihre Aktivität vor allen Überwachungstools zu verbergen.',
    passDetail: 'ETW-Anbieter intakt. Keine Patching-Indikatoren in ntdll.dll.',
    fixActionsTemplate: ['ETW-Anbieterregistrierung wiederherstellen', 'ntdll.dll-Integrität prüfen', 'ETW-Audit-Logging aktivieren'],
    preserves: ['System-Logging', 'Leistungsüberwachung'],
    canUndo: false,
  },
  'process-hollowing': {
    whatChecked: 'Laufende Prozesse auf Anzeichen von Process Hollowing (legitimer Prozess mit ersetztem Code).',
    riskExplanation: 'Process Hollowing lässt Malware in vertrauenswürdigen Prozessen wie svchost.exe laufen und umgeht so Anwendungs-Whitelisting und Firewalls.',
    passDetail: 'Keine Prozesse zeigen Hollowing-Indikatoren. Image-Pfade stimmen mit erwarteten Speicherorten überein.',
    fixActionsTemplate: ['Verdächtige gehöhlte Prozesse beenden', 'Betroffene Executables scannen', 'Zur Watchlist hinzufügen'],
    preserves: ['Legitime Prozesse unberührt'],
    canUndo: false,
  },
  'reflective-dll': {
    whatChecked: 'Speicherbereiche auf Reflective-DLL-Injection-Signaturen (PE-Header in Nicht-Image-Speicher).',
    riskExplanation: 'Reflective DLL Injection lädt Schadcode direkt in den Speicher, ohne die Festplatte zu berühren, und umgeht so Antivirus-Dateiscans.',
    passDetail: 'Keine Reflective-DLL-Injection-Signaturen im Prozessspeicher gefunden.',
    fixActionsTemplate: ['Betroffene Prozesse beenden', 'Verdächtige Speicherbereiche zur Analyse sichern', 'Exploit-Schutz aktivieren'],
    preserves: ['Laufende Anwendungen', 'Systemstabilität'],
    canUndo: false,
  },
  'lsass-protection': {
    whatChecked: 'LSASS (Local Security Authority) Prozessschutzebene und Credential-Guard-Status.',
    riskExplanation: 'LSASS speichert Authentifizierungsdaten. Ohne Schutz können Tools wie Mimikatz alle Passwörter aus dem Speicher auslesen.',
    passDetail: 'LSASS läuft als Protected Process Light (PPL). Credential Guard aktiviert.',
    fixActionsTemplate: ['RunAsPPL für LSASS aktivieren', 'Credential Guard über Gruppenrichtlinie aktivieren', 'LSASS-Speicherzugriff blockieren'],
    preserves: ['Authentifizierungsfunktionalität', 'Domänenanmeldung'],
    canUndo: true,
    undoPath: 'Registry → LSA → RunAsPPL=0',
  },
  'ransomware-entropy': {
    whatChecked: 'Dateisystem-Entropieanalyse auf Anzeichen aktiver Verschlüsselung (Ransomware-Indikator).',
    riskExplanation: 'Ransomware verschlüsselt Dateien und erhöht deren Entropie dramatisch. Früherkennung kann die Verschlüsselung stoppen, bevor kritische Daten verloren gehen.',
    passDetail: 'Datei-Entropie im normalen Bereich. Keine Massenverschlüsselung erkannt.',
    fixActionsTemplate: ['Überwachten Ordnerzugriff aktivieren', 'Verdächtige Schreibvorgänge blockieren', 'Dateisystem-Honeypots erstellen'],
    preserves: ['Normale Dateioperationen', 'Anwendungsdatenzugriff'],
    canUndo: true,
    undoPath: 'Windows-Sicherheit → Überwachter Ordnerzugriff → Aus',
  },
  'honeypot-mesh': {
    whatChecked: 'Ob Sentinel-Honeypot-Dateien und Canary-Tokens für Frühwarnung bei Einbrüchen eingerichtet sind.',
    riskExplanation: 'Honeypots erkennen Angreifer, die den Perimeter bereits durchbrochen haben. Ohne sie bleibt laterale Bewegung unbemerkt.',
    passDetail: 'Honeypot-Netz eingerichtet. Canary-Tokens aktiv.',
    fixActionsTemplate: ['Honeypot-Dateien in häufigen Verzeichnissen platzieren', 'Canary-Token-Überwachung einrichten'],
    preserves: ['Keine sichtbaren Änderungen für Benutzer', 'Normales Dateibrowsing'],
    canUndo: true,
    undoPath: 'Honeypot-Dateien aus überwachten Verzeichnissen entfernen',
  },
  'wmi-persistence': {
    whatChecked: 'WMI-Event-Abonnements auf Persistenzmechanismen (häufige Malware-Technik).',
    riskExplanation: 'WMI-Persistenz überlebt Neustarts und ist für die meisten Benutzer unsichtbar. Malware nutzt sie, um sich nach jedem Neustart neu zu starten.',
    passDetail: 'Keine verdächtigen WMI-Event-Abonnements gefunden.',
    fixActionsTemplate: ['Bösartige WMI-Abonnements entfernen', 'WMI-Aktivität protokollieren', 'Auf neue Abonnements überwachen'],
    preserves: ['Legitime WMI-Abonnements', 'Management-Tools'],
    canUndo: false,
  },
  'code-integrity': {
    whatChecked: 'Windows Code Integrity (CI) Richtlinie, Treibersignatur-Erzwingung und HVCI-Status.',
    riskExplanation: 'Ohne Code-Integritäts-Erzwingung können unsignierte Treiber und Kernel-Module geladen werden — das ermöglicht Rootkits.',
    passDetail: 'Code-Integrität aktiviert. HVCI aktiv. Nur signierte Treiber erlaubt.',
    fixActionsTemplate: ['HVCI (Hypervisor-geschützte Code-Integrität) aktivieren', 'Treibersignierung erzwingen', 'Audit-Modus zuerst aktivieren'],
    preserves: ['Signierte Treiber funktionieren weiter', 'Die meisten Anwendungen unberührt'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinie → Device Guard → HVCI deaktivieren',
  },
  'exploit-protection': {
    whatChecked: 'Windows Exploit-Schutz-Einstellungen: DEP, ASLR, CFG, SEHOP für System und kritische Prozesse.',
    riskExplanation: 'Exploit-Mitigationen verhindern Speichermanipulationsangriffe. Ohne sie gelingen Buffer Overflows und ROP-Chains trivial.',
    passDetail: 'DEP systemweit aktiviert. ASLR aktiv. CFG für kritische Prozesse erzwungen.',
    fixActionsTemplate: ['Alle Exploit-Schutz-Mitigationen aktivieren', 'Auf kritische Systemprozesse anwenden', 'Audit-Modus für Kompatibilität aktivieren'],
    preserves: ['Anwendungskompatibilität (meiste Apps)', 'Systemstabilität'],
    canUndo: true,
    undoPath: 'Windows-Sicherheit → Exploit-Schutz → Auf Standard zurücksetzen',
  },
  'attack-surface-reduction': {
    whatChecked: 'ASR-Regeln-Status: Office-Makro-Ausführung, Credential-Diebstahl, Skript-Obfuskations-Blockierung.',
    riskExplanation: 'ASR-Regeln blockieren die häufigsten Angriffsvektoren. Ohne sie gelingen bösartige Office-Makros und skriptbasierte Angriffe.',
    passDetail: 'ASR-Regeln im Block-Modus für kritische Kategorien aktiviert.',
    fixActionsTemplate: ['ASR-Regeln über Gruppenrichtlinie aktivieren', 'Kritische Regeln auf Block-Modus setzen', 'Audit-Modus zum Testen aktivieren'],
    preserves: ['Normale Office-Nutzung', 'Legitime Skripte mit Ausnahmen'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinie → ASR-Regeln → Deaktivieren',
  },
  'network-level-auth': {
    whatChecked: 'Network Level Authentication (NLA) Anforderung für Remotedesktop-Verbindungen.',
    riskExplanation: 'Ohne NLA können Angreifer den RDP-Anmeldebildschirm ohne Authentifizierung erreichen — Brute-Force und RDP-Exploits werden möglich.',
    passDetail: 'NLA für alle RDP-Verbindungen erforderlich.',
    fixActionsTemplate: ['NLA-Anforderung aktivieren', 'RDP deaktivieren falls nicht benötigt', 'RDP auf bestimmte IPs beschränken'],
    preserves: ['Legitime RDP-Verbindungen mit NLA-fähigen Clients'],
    canUndo: true,
    undoPath: 'Systemeigenschaften → Remote → NLA-Anforderung deaktivieren',
  },
  'defender-status': {
    whatChecked: 'Windows Defender Echtzeitschutz, Cloud-Schutz, Definitionsalter und Manipulationsschutz.',
    riskExplanation: 'Defender ist der Basis-Virenschutz. Wenn deaktiviert oder veraltet, hat das System keinerlei Malware-Schutz.',
    passDetail: 'Defender aktiv. Echtzeitschutz ein. Definitionen aktuell. Manipulationsschutz aktiviert.',
    fixActionsTemplate: ['Echtzeitschutz aktivieren', 'Definitionen aktualisieren', 'Manipulationsschutz aktivieren', 'Cloud-basierten Schutz aktivieren'],
    preserves: ['Systemleistung', 'Anwendungskompatibilität'],
    canUndo: true,
    undoPath: 'Windows-Sicherheit → Viren- & Bedrohungsschutz → Einstellungen',
  },
  'scheduled-task-audit': {
    whatChecked: 'Geplante Aufgaben auf verdächtige Einträge: unbekannte Herausgeber, codierte Befehle, ungewöhnliche Auslöser.',
    riskExplanation: 'Bösartige geplante Aufgaben bieten Persistenz und können Payloads bei Boot, Anmeldung oder zeitgesteuert ohne Benutzerwissen ausführen.',
    passDetail: 'Alle geplanten Aufgaben von bekannten Herausgebern. Keine codierten Befehlspayloads.',
    fixActionsTemplate: ['Verdächtige geplante Aufgaben entfernen', 'Aufgabenerstellungs-Auditing aktivieren', 'Unsignierte Aufgaben-Executables blockieren'],
    preserves: ['System-Wartungsaufgaben', 'Anwendungs-Update-Aufgaben'],
    canUndo: false,
  },
  'service-audit': {
    whatChecked: 'Windows-Dienste auf unsignierte Binärdateien, ungewöhnliche Dienstkonten und verdächtige Dienstpfade.',
    riskExplanation: 'Bösartige Dienste laufen auf SYSTEM-Ebene mit vollen Rechten. Sie überleben Neustarts und sind schwer zu erkennen.',
    passDetail: 'Alle Dienste haben signierte Binärdateien. Keine verdächtigen Dienstpfade erkannt.',
    fixActionsTemplate: ['Verdächtige Dienste deaktivieren', 'Dienst-Binärsignaturen verifizieren', 'Diensterstellungsberechtigungen einschränken'],
    preserves: ['Legitime Systemdienste', 'Anwendungsdienste'],
    canUndo: false,
  },
  'autorun-entries': {
    whatChecked: 'Registry-Autorun-Schlüssel, Startup-Ordner-Einträge und Shell-Erweiterungen für Persistenz.',
    riskExplanation: 'Autorun-Einträge werden bei jeder Anmeldung ausgeführt. Malware nutzt häufig Run/RunOnce-Registry-Schlüssel zur Persistenz.',
    passDetail: 'Alle Autorun-Einträge von verifizierten Herausgebern.',
    fixActionsTemplate: ['Unbekannte Autorun-Einträge entfernen', 'Autorun-Auditing aktivieren', 'Registry-Autorun-Schlüssel sperren'],
    preserves: ['Legitime Startprogramme'],
    canUndo: true,
    undoPath: 'Registry → Run/RunOnce → Einträge wieder hinzufügen',
  },
  'powershell-logging': {
    whatChecked: 'PowerShell Script-Block-Logging, Modul-Logging und Transkriptions-Einstellungen.',
    riskExplanation: 'Ohne PowerShell-Logging hinterlassen dateilose Angriffe keine forensischen Beweise. Alle bösartigen PowerShell-Aktivitäten sind unsichtbar.',
    passDetail: 'Script-Block-Logging aktiviert. Modul-Logging aktiv. Transkription konfiguriert.',
    fixActionsTemplate: ['ScriptBlockLogging aktivieren', 'ModuleLogging aktivieren', 'Transkriptions-Ausgabepfad konfigurieren'],
    preserves: ['PowerShell-Funktionalität unverändert', 'Geringe Leistungsauswirkung'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinie → PowerShell → Logging deaktivieren',
  },
  'sysmon-status': {
    whatChecked: 'Ob Sysmon (System Monitor) installiert und für erweitertes Event-Logging konfiguriert ist.',
    riskExplanation: 'Sysmon liefert detailliertes Logging für Prozesserstellung, Netzwerkverbindungen und Dateimodifikationen — essentiell für Threat Hunting.',
    passDetail: 'Sysmon installiert und mit aktiver Konfiguration laufend.',
    fixActionsTemplate: ['Sysmon von Sysinternals installieren', 'Empfohlene Konfiguration anwenden'],
    preserves: ['Systemleistung (minimale Auswirkung)', 'Bestehende Event-Logs'],
    canUndo: true,
    undoPath: 'Sysmon -u (deinstallieren)',
  },
  'dll-search-order': {
    whatChecked: 'DLL-Suchreihenfolge-Härtung: SafeDllSearchMode, KnownDLLs-Schutz, CWD-Entfernung aus Suchpfad.',
    riskExplanation: 'DLL-Suchreihenfolge-Hijacking ermöglicht Angreifern, bösartige DLLs zu platzieren, die von legitimen Anwendungen geladen werden.',
    passDetail: 'SafeDllSearchMode aktiviert. CWD aus Standard-Suchpfad entfernt.',
    fixActionsTemplate: ['SafeDllSearchMode aktivieren', 'CWDIllegalInDllSearch konfigurieren', 'Geladene DLLs auditieren'],
    preserves: ['Anwendungskompatibilität (meiste Apps)', 'System-DLL-Laden'],
    canUndo: true,
    undoPath: 'Registry → Session Manager → SafeDllSearchMode=0',
  },
  'named-pipe-audit': {
    whatChecked: 'Named Pipes auf verdächtige C2-Kommunikationskanäle (Cobalt Strike, Metasploit-Indikatoren).',
    riskExplanation: 'Named Pipes werden von Post-Exploitation-Frameworks für Inter-Prozess-Kommunikation und laterale Bewegung verwendet.',
    passDetail: 'Keine verdächtigen Named Pipes erkannt. Alle Pipes von bekannten Systemdiensten.',
    fixActionsTemplate: ['Verdächtige Named Pipes schließen', 'Pipe-Erstellung von nicht vertrauenswürdigen Prozessen blockieren', 'Pipe-Auditing aktivieren'],
    preserves: ['System-IPC-Funktionalität', 'Anwendungskommunikation'],
    canUndo: false,
  },
  'syscall-integrity': {
    whatChecked: 'Ob direkte Syscall-Aufrufe überwacht werden (Umgehungserkennung für Userland-API-Hooking).',
    riskExplanation: 'Fortgeschrittene Malware umgeht Antivirus durch direkte NT-Syscall-Aufrufe und überspringt gehookte APIs. Ohne Syscall-Überwachung ist EDR blind.',
    passDetail: 'Syscall-Überwachung aktiv. HVCI verhindert unautorisierte Kernel-Übergänge.',
    fixActionsTemplate: ['Kernel Patch Protection-Verifizierung aktivieren', 'ETW für Syscall-Tracing konfigurieren', 'HVCI aktivieren'],
    preserves: ['Normale Anwendungsausführung', 'Geringe Leistungsauswirkung möglich'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinie → HVCI → Deaktivieren',
  },
  'etw-threat-intelligence': {
    whatChecked: 'ETW Microsoft-Windows-Threat-Intelligence Anbieterstatus.',
    riskExplanation: 'ETW-TI liefert Kernel-Level-Telemetrie über Prozessinjektion, Speichermanipulation und andere bösartige Techniken. Deaktivierung macht alle Sicherheitssoftware blind.',
    passDetail: 'ETW-TI-Anbieter aktiviert und aktiv. Keine Manipulationsindikatoren.',
    fixActionsTemplate: ['ETW-TI-Anbieter verifizieren', 'Auf bekannte ETW-TI-Bypass-Techniken prüfen', 'HVCI aktivieren um Kernel-Level-Manipulation zu verhindern'],
    preserves: ['Keine sichtbare Benutzerauswirkung', 'Geringe Telemetrie-Belastung'],
    canUndo: false,
  },
  'apc-injection-monitor': {
    whatChecked: 'Ob APC (Asynchronous Procedure Call) Injection in fremde Prozesse überwacht wird.',
    riskExplanation: 'APC-Injection wird von Malware verwendet, um Code in legitimen Prozessen auszuführen, ohne neue Threads zu erstellen — das umgeht Erkennung.',
    passDetail: 'APC-Injection-Überwachung aktiv. Keine Cross-Prozess-APC-Anomalien erkannt.',
    fixActionsTemplate: ['ETW APC-Überwachung aktivieren', 'Sentinel für Alarmierung bei Cross-Prozess-APC-Queuing konfigurieren'],
    preserves: ['Normale Anwendungsfunktionalität'],
    canUndo: true,
    undoPath: 'Sentinel → Einstellungen → EDR → APC-Überwachung deaktivieren',
  },
  'parent-pid-spoofing': {
    whatChecked: 'Ob Prozesserstellungs-Auditing Parent-PID-Spoofing erkennt (PPID-Diskrepanzen).',
    riskExplanation: 'Malware fälscht Parent-PIDs, um als Kindprozesse vertrauenswürdiger Prozesse (wie explorer.exe) zu erscheinen und prozessbaum-basierte Erkennung zu umgehen.',
    passDetail: 'Prozesserstellungs-Auditing aktiv. PPID-Validierung aktiviert.',
    fixActionsTemplate: ['Prozesserstellungs-Auditing aktivieren (Event ID 4688)', 'Befehlszeilen-Logging in Audit-Richtlinie aktivieren', 'Sentinel für PPID-Diskrepanz-Erkennung konfigurieren'],
    preserves: ['Normale Prozesserstellung', 'Leichte Erhöhung des Audit-Log-Volumens'],
    canUndo: true,
    undoPath: 'Audit-Richtlinie → Prozesserstellung → Deaktivieren',
  },
  'token-elevation-guard': {
    whatChecked: 'Token-Privilegien-Eskalationsüberwachung und UAC-Bypass-Erkennung.',
    riskExplanation: 'Token-Manipulation ermöglicht Malware, sich von Benutzer- auf SYSTEM-Privilegien zu erheben, ohne UAC-Eingabeaufforderungen auszulösen.',
    passDetail: 'Token-Elevations-Überwachung aktiv. Keine verdächtigen Privilegien-Eskalationen erkannt.',
    fixActionsTemplate: ['Token-Audit-Logging aktivieren', 'UAC auf „Immer benachrichtigen" setzen', 'Auf bekannte UAC-Bypass-Techniken überwachen'],
    preserves: ['Normale UAC-Funktionalität', 'Admin-Operationen unberührt'],
    canUndo: true,
    undoPath: 'UAC-Einstellungen → Vorherige Stufe wiederherstellen',
  },
  'shadow-stack': {
    whatChecked: 'Hardware-erzwungener Shadow Stack (CET) Status für Rücksprungadressen-Schutz.',
    riskExplanation: 'Shadow Stack verhindert Return-Oriented Programming (ROP) Angriffe durch eine hardware-geschützte Kopie der Rücksprungadressen.',
    passDetail: 'CET Shadow Stack für kompatible Anwendungen aktiviert.',
    fixActionsTemplate: ['CET über Windows-Sicherheit aktivieren', 'Auf kritische Systemprozesse anwenden'],
    preserves: ['Anwendungskompatibilität', 'Meiste Software unberührt'],
    canUndo: true,
    undoPath: 'Windows-Sicherheit → Exploit-Schutz → Shadow Stack deaktivieren',
  },
  'boot-integrity': {
    whatChecked: 'Measured Boot, Boot-Log-Integrität und Early-Launch Anti-Malware (ELAM) Status.',
    riskExplanation: 'Boot-Level-Angriffe (Bootkits) laden vor dem Betriebssystem und sind für alle Laufzeit-Sicherheitstools unsichtbar.',
    passDetail: 'Measured Boot aktiv. ELAM-Treiber geladen. Boot-Log-Integrität verifiziert.',
    fixActionsTemplate: ['Measured Boot aktivieren', 'ELAM-Treiberregistrierung verifizieren', 'Boot-Log auf Manipulation prüfen'],
    preserves: ['Boot-Leistung', 'OS-Startsequenz'],
    canUndo: false,
  },
  'memory-integrity': {
    whatChecked: 'Speicherintegrität (HVCI) Erzwingungsstatus und Blockliste verwundbarer Treiber.',
    riskExplanation: 'Ohne Speicherintegrität kann Kernel-Mode-Code zur Laufzeit modifiziert werden — das ermöglicht Rootkits und Kernel-Exploits.',
    passDetail: 'Speicherintegrität (HVCI) aktiviert. Blockliste verwundbarer Treiber aktiv.',
    fixActionsTemplate: ['Speicherintegrität in Windows-Sicherheit aktivieren', 'Blockliste verwundbarer Treiber aktualisieren'],
    preserves: ['Meiste Treiber und Anwendungen', 'Einige ältere Treiber benötigen ggf. Updates'],
    canUndo: true,
    undoPath: 'Windows-Sicherheit → Gerätesicherheit → Kernisolierung → Aus',
  },
  'credential-dump-protection': {
    whatChecked: 'Schutz gegen Credential-Dumping: WDigest-Klartextspeicherung, LSA-Schutz, Credential Guard.',
    riskExplanation: 'WDigest speichert Passwörter im Klartext im Speicher. Ohne Schutz kann jeder Admin-Prozess alle angemeldeten Zugangsdaten auslesen.',
    passDetail: 'WDigest-Klartext deaktiviert. LSA-Schutz aktiviert.',
    fixActionsTemplate: ['WDigest UseLogonCredential deaktivieren', 'LSA RunAsPPL aktivieren', 'Credential Guard aktivieren'],
    preserves: ['Authentifizierungsfunktionalität', 'SSO und Domänen-Authentifizierung'],
    canUndo: true,
    undoPath: 'Registry → WDigest → UseLogonCredential=1',
  },
  'com-hijacking': {
    whatChecked: 'Benutzer-COM-CLSID-Einträge auf potenzielle COM-Hijacking-Persistenz.',
    riskExplanation: 'COM-Hijacking ermöglicht Malware, legitime COM-Aufrufe abzufangen und schädlichen Code bei jeder Nutzung des gekaperten COM-Objekts auszuführen.',
    passDetail: 'Benutzer-CLSID-Anzahl im normalen Bereich. Keine verdächtigen COM-Registrierungen.',
    fixActionsTemplate: ['Benutzer-CLSIDs in HKCU\\SOFTWARE\\Classes\\CLSID auditieren', 'Verdächtige COM-Registrierungen entfernen', 'Neue Benutzer-COM-Einträge überwachen'],
    preserves: ['Anwendungs-COM-Funktionalität', 'System-COM-Objekte'],
    canUndo: false,
  },
  'sandbox-capabilities': {
    whatChecked: 'Network-Protection-Status und Windows-Sandbox-Verfügbarkeit.',
    riskExplanation: 'Ohne Sandbox-Fähigkeiten werden schädliche Dateien und Skripte im vollen Benutzerkontext mit Zugriff auf alle Daten und Netzwerkressourcen ausgeführt.',
    passDetail: 'Network Protection aktiviert. Sandbox für isolierte Ausführung verfügbar.',
    fixActionsTemplate: ['Network Protection aktivieren', 'Windows-Sandbox-Feature installieren', 'Application Guard aktivieren'],
    preserves: ['Netzwerkverbindung', 'Anwendungszugriff'],
    canUndo: true,
    undoPath: 'Set-MpPreference -EnableNetworkProtection 0',
  },
  'behavior-analysis': {
    whatChecked: 'Laufende Prozesse auf anomales Verhalten: unsignierte Programme mit hohem CPU/RAM-Verbrauch.',
    riskExplanation: 'Kryptominer und Datenexfiltrationstools laufen oft als unsignierte Prozesse mit abnormal hohem Ressourcenverbrauch.',
    passDetail: 'Keine unsignierten Hochressourcen-Prozesse erkannt.',
    fixActionsTemplate: ['PUA-Schutz in Defender aktivieren', 'Network Protection aktivieren', 'Markierte Prozesse untersuchen'],
    preserves: ['Legitime Anwendungen', 'Systemleistung'],
    canUndo: false,
  },
  'critical-file-protection': {
    whatChecked: 'ACLs auf kritischen Systemdateien (hosts, Treiber, Boot-Konfiguration) auf benutzer-beschreibbare Berechtigungen.',
    riskExplanation: 'Wenn Standardbenutzer kritische Systemdateien beschreiben können, kann Malware DNS umleiten, Rootkits installieren oder die Boot-Konfiguration ändern.',
    passDetail: 'Kritische Systemdateien korrekt geschützt. Keine benutzer-beschreibbaren Schwachstellen.',
    fixActionsTemplate: ['ACLs auf kritischen Dateien zurücksetzen', 'Benutzer-Schreibberechtigungen entfernen', 'Datei-Integritätsüberwachung aktivieren'],
    preserves: ['Dateizugriff für Admins', 'Systemfunktionalität'],
    canUndo: false,
  },
  'handle-monitor': {
    whatChecked: 'Handle-Anzahl auf LSASS-Prozess — abnormal hohe Werte deuten auf Credential-Dumping-Tools hin.',
    riskExplanation: 'Tools wie Mimikatz öffnen viele Handles zu LSASS zum Credential-Dump. Hohe Handle-Zahlen sind ein starker Indikator für aktiven Passwort-Diebstahl.',
    passDetail: 'LSASS-Handle-Anzahl im normalen Bereich. Keine Credential-Dumping-Indikatoren.',
    fixActionsTemplate: ['LSASS-PPL-Schutz aktivieren', 'ASR-Regel für Credential-Stealing aktivieren', 'Hohe Handle-Anzahl untersuchen'],
    preserves: ['Authentifizierungsfunktionalität', 'System-Anmeldung'],
    canUndo: false,
  },
};
