/**
 * SENTINEL — EDR, Kernel & Performance Scan Check Detail Definitions
 * Each check defines its detail template. Runtime data fills in the blanks.
 */

import type { CheckDetailTemplate } from './networkScanChecks';

// ═══════════════════════════════════════════════════════════════
// EDR & BEHAVIORAL — 24 checks
// ═══════════════════════════════════════════════════════════════

export const EDR_CHECK_DETAILS: Record<string, CheckDetailTemplate> = {
  'amsi-status': {
    whatChecked: 'Antimalware Scan Interface (AMSI) provider registration and bypass detection.',
    riskExplanation: 'AMSI is the first line of defense against fileless malware. If bypassed or disabled, PowerShell and VBScript attacks execute undetected.',
    passDetail: 'AMSI provider registered and active. No bypass indicators detected.',
    fixActionsTemplate: ['Re-register AMSI provider DLL', 'Check for AMSI bypass patches in memory', 'Enable AMSI logging'],
    preserves: ['PowerShell functionality', 'Script execution unchanged'],
    canUndo: false,
  },
  'etw-integrity': {
    whatChecked: 'Event Tracing for Windows (ETW) provider status and tampering indicators.',
    riskExplanation: 'ETW is how Windows logs security events. Advanced malware patches ETW to hide its activity from all monitoring tools.',
    passDetail: 'ETW providers intact. No patching indicators in ntdll.dll.',
    fixActionsTemplate: ['Restore ETW provider registration', 'Check ntdll.dll integrity', 'Enable ETW audit logging'],
    preserves: ['System logging', 'Performance monitoring'],
    canUndo: false,
  },
  'process-hollowing': {
    whatChecked: 'Running processes for signs of process hollowing (legitimate process with replaced code).',
    riskExplanation: 'Process hollowing lets malware run inside trusted processes like svchost.exe, bypassing application whitelisting and firewalls.',
    passDetail: 'No processes show hollowing indicators. Image paths match expected locations.',
    fixActionsTemplate: ['Terminate suspicious hollowed processes', 'Scan affected executables', 'Add to watchlist'],
    preserves: ['Legitimate processes unaffected'],
    canUndo: false,
  },
  'reflective-dll': {
    whatChecked: 'Memory regions for reflective DLL injection signatures (PE headers in non-image memory).',
    riskExplanation: 'Reflective DLL injection loads malicious code directly into memory without touching disk, evading antivirus file scans.',
    passDetail: 'No reflective DLL injection signatures found in process memory.',
    fixActionsTemplate: ['Terminate affected processes', 'Dump suspicious memory regions for analysis', 'Enable exploit protection'],
    preserves: ['Running applications', 'System stability'],
    canUndo: false,
  },
  'lsass-protection': {
    whatChecked: 'LSASS (Local Security Authority) process protection level and credential guard status.',
    riskExplanation: 'LSASS stores authentication credentials. Without protection, tools like Mimikatz can dump all passwords from memory.',
    passDetail: 'LSASS running as Protected Process Light (PPL). Credential Guard enabled.',
    fixActionsTemplate: ['Enable RunAsPPL for LSASS', 'Enable Credential Guard via Group Policy', 'Block LSASS memory access'],
    preserves: ['Authentication functionality', 'Domain login'],
    canUndo: true,
    undoPath: 'Registry → LSA → RunAsPPL=0',
  },
  'ransomware-entropy': {
    whatChecked: 'File system entropy analysis for signs of active encryption (ransomware indicator).',
    riskExplanation: 'Ransomware encrypts files, dramatically increasing their entropy. Early detection can stop encryption before critical data is lost.',
    passDetail: 'File entropy within normal ranges. No mass encryption detected.',
    fixActionsTemplate: ['Enable controlled folder access', 'Block suspicious write operations', 'Create file system honeypots'],
    preserves: ['Normal file operations', 'Application data access'],
    canUndo: true,
    undoPath: 'Windows Security → Controlled Folder Access → Off',
  },
  'honeypot-mesh': {
    whatChecked: 'Whether Sentinel honeypot files and canary tokens are deployed for early breach detection.',
    riskExplanation: 'Honeypots detect attackers who have already breached the perimeter. Without them, lateral movement goes unnoticed.',
    passDetail: 'Honeypot mesh deployed. Canary tokens active.',
    fixActionsTemplate: ['Deploy honeypot files in common directories', 'Set up canary token monitoring'],
    preserves: ['No user-visible changes', 'Normal file browsing'],
    canUndo: true,
    undoPath: 'Remove honeypot files from monitored directories',
  },
  'wmi-persistence': {
    whatChecked: 'WMI event subscriptions for persistence mechanisms (common malware technique).',
    riskExplanation: 'WMI persistence survives reboots and is invisible to most users. Malware uses it to re-launch after every restart.',
    passDetail: 'No suspicious WMI event subscriptions found.',
    fixActionsTemplate: ['Remove malicious WMI subscriptions', 'Log WMI activity', 'Monitor for new subscriptions'],
    preserves: ['Legitimate WMI subscriptions', 'Management tools'],
    canUndo: false,
  },
  'code-integrity': {
    whatChecked: 'Windows Code Integrity (CI) policy, driver signing enforcement, and HVCI status.',
    riskExplanation: 'Without code integrity enforcement, unsigned drivers and kernel modules can be loaded, enabling rootkits.',
    passDetail: 'Code integrity enabled. HVCI active. Only signed drivers allowed.',
    fixActionsTemplate: ['Enable HVCI (Hypervisor-protected Code Integrity)', 'Enforce driver signing', 'Enable audit mode first'],
    preserves: ['Signed drivers continue working', 'Most applications unaffected'],
    canUndo: true,
    undoPath: 'Group Policy → Device Guard → Disable HVCI',
  },
  'exploit-protection': {
    whatChecked: 'Windows Exploit Protection settings: DEP, ASLR, CFG, SEHOP for system and critical processes.',
    riskExplanation: 'Exploit mitigations prevent memory corruption attacks. Without them, buffer overflows and ROP chains succeed trivially.',
    passDetail: 'DEP enabled system-wide. ASLR active. CFG enforced on critical processes.',
    fixActionsTemplate: ['Enable all exploit protection mitigations', 'Apply to critical system processes', 'Enable audit mode for compatibility'],
    preserves: ['Application compatibility (most apps)', 'System stability'],
    canUndo: true,
    undoPath: 'Windows Security → Exploit Protection → Reset to defaults',
  },
  'attack-surface-reduction': {
    whatChecked: 'ASR rules status: Office macro execution, credential stealing, script obfuscation blocking.',
    riskExplanation: 'ASR rules block the most common attack vectors. Without them, malicious Office macros and script-based attacks succeed.',
    passDetail: 'ASR rules enabled in block mode for critical categories.',
    fixActionsTemplate: ['Enable ASR rules via Group Policy', 'Set critical rules to Block mode', 'Enable audit mode for testing'],
    preserves: ['Normal Office usage', 'Legitimate scripts with exceptions'],
    canUndo: true,
    undoPath: 'Group Policy → ASR Rules → Disable',
  },
  'network-level-auth': {
    whatChecked: 'Network Level Authentication (NLA) requirement for Remote Desktop connections.',
    riskExplanation: 'Without NLA, attackers can reach the RDP login screen without authentication, enabling brute force and exploitation of RDP vulnerabilities.',
    passDetail: 'NLA required for all RDP connections.',
    fixActionsTemplate: ['Enable NLA requirement', 'Disable RDP if not needed', 'Restrict RDP to specific IPs'],
    preserves: ['Legitimate RDP connections with NLA-capable clients'],
    canUndo: true,
    undoPath: 'System Properties → Remote → Uncheck NLA requirement',
  },
  'defender-status': {
    whatChecked: 'Windows Defender real-time protection, cloud protection, definitions age, and tamper protection.',
    riskExplanation: 'Defender is the baseline AV. If disabled or outdated, the system has zero malware protection.',
    passDetail: 'Defender active. Real-time protection on. Definitions current. Tamper protection enabled.',
    fixActionsTemplate: ['Enable real-time protection', 'Update definitions', 'Enable tamper protection', 'Enable cloud-delivered protection'],
    preserves: ['System performance', 'Application compatibility'],
    canUndo: true,
    undoPath: 'Windows Security → Virus & Threat Protection → Settings',
  },
  'scheduled-task-audit': {
    whatChecked: 'Scheduled tasks for suspicious entries: unknown publishers, encoded commands, unusual triggers.',
    riskExplanation: 'Malicious scheduled tasks provide persistence and can execute payloads at boot, login, or on a timer without user awareness.',
    passDetail: 'All scheduled tasks from known publishers. No encoded command payloads.',
    fixActionsTemplate: ['Remove suspicious scheduled tasks', 'Enable task creation auditing', 'Block unsigned task executables'],
    preserves: ['System maintenance tasks', 'Application update tasks'],
    canUndo: false,
  },
  'service-audit': {
    whatChecked: 'Windows services for unsigned binaries, unusual service accounts, and suspicious service paths.',
    riskExplanation: 'Malicious services run at SYSTEM level with full privileges. They persist across reboots and are hard to detect.',
    passDetail: 'All services have signed binaries. No suspicious service paths detected.',
    fixActionsTemplate: ['Disable suspicious services', 'Verify service binary signatures', 'Restrict service creation permissions'],
    preserves: ['Legitimate system services', 'Application services'],
    canUndo: false,
  },
  'autorun-entries': {
    whatChecked: 'Registry autorun keys, startup folder entries, and shell extensions for persistence.',
    riskExplanation: 'Autorun entries execute at every login. Malware commonly uses Run/RunOnce registry keys for persistence.',
    passDetail: 'All autorun entries from verified publishers.',
    fixActionsTemplate: ['Remove unknown autorun entries', 'Enable autorun auditing', 'Lock registry autorun keys'],
    preserves: ['Legitimate startup applications'],
    canUndo: true,
    undoPath: 'Registry → Run/RunOnce → Re-add entries',
  },
  'powershell-logging': {
    whatChecked: 'PowerShell script block logging, module logging, and transcription settings.',
    riskExplanation: 'Without PowerShell logging, fileless attacks leave no forensic evidence. All malicious PowerShell activity is invisible.',
    passDetail: 'Script block logging enabled. Module logging active. Transcription configured.',
    fixActionsTemplate: ['Enable ScriptBlockLogging', 'Enable ModuleLogging', 'Configure transcription output path'],
    preserves: ['PowerShell functionality unchanged', 'Slight performance impact'],
    canUndo: true,
    undoPath: 'Group Policy → PowerShell → Disable logging',
  },
  'sysmon-status': {
    whatChecked: 'Whether Sysmon (System Monitor) is installed and configured for advanced event logging.',
    riskExplanation: 'Sysmon provides detailed process creation, network connection, and file modification logging essential for threat hunting.',
    passDetail: 'Sysmon installed and running with active configuration.',
    fixActionsTemplate: ['Install Sysmon from Sysinternals', 'Apply recommended configuration'],
    preserves: ['System performance (minimal impact)', 'Existing event logs'],
    canUndo: true,
    undoPath: 'Sysmon -u (uninstall)',
  },
  'dll-search-order': {
    whatChecked: 'DLL search order hardening: SafeDllSearchMode, KnownDLLs protection, CWD removal from search path.',
    riskExplanation: 'DLL search order hijacking lets attackers place malicious DLLs that get loaded by legitimate applications.',
    passDetail: 'SafeDllSearchMode enabled. CWD removed from default search path.',
    fixActionsTemplate: ['Enable SafeDllSearchMode', 'Configure CWDIllegalInDllSearch', 'Audit loaded DLLs'],
    preserves: ['Application compatibility (most apps)', 'System DLL loading'],
    canUndo: true,
    undoPath: 'Registry → Session Manager → SafeDllSearchMode=0',
  },
  'named-pipe-audit': {
    whatChecked: 'Named pipes for suspicious C2 communication channels (Cobalt Strike, Metasploit indicators).',
    riskExplanation: 'Named pipes are used by post-exploitation frameworks for inter-process communication and lateral movement.',
    passDetail: 'No suspicious named pipes detected. All pipes from known system services.',
    fixActionsTemplate: ['Close suspicious named pipes', 'Block pipe creation from untrusted processes', 'Enable pipe auditing'],
    preserves: ['System IPC functionality', 'Application communication'],
    canUndo: false,
  },
  'syscall-integrity': {
    whatChecked: 'Whether direct syscall invocation is monitored (userland API hooking bypass detection).',
    riskExplanation: 'Advanced malware bypasses antivirus by calling NT syscalls directly, skipping hooked APIs. Without syscall monitoring, EDR is blind to sophisticated attacks.',
    passDetail: 'Syscall monitoring active. HVCI preventing unauthorized kernel transitions.',
    fixActionsTemplate: ['Enable Kernel Patch Protection verification', 'Configure ETW for syscall tracing', 'Enable Hypervisor-protected Code Integrity (HVCI)'],
    preserves: ['Normal application execution', 'Slight performance overhead possible'],
    canUndo: true,
    undoPath: 'Group Policy → HVCI → Disable',
  },
  'etw-threat-intelligence': {
    whatChecked: 'ETW (Event Tracing for Windows) Microsoft-Windows-Threat-Intelligence provider status.',
    riskExplanation: 'ETW-TI provides kernel-level telemetry on process injection, memory manipulation, and other malicious techniques. Disabling it blinds all security software.',
    passDetail: 'ETW-TI provider enabled and active. No tampering indicators.',
    fixActionsTemplate: ['Verify ETW-TI provider is enabled and not tampered', 'Check for known ETW-TI bypass techniques', 'Enable HVCI to prevent kernel-level tampering'],
    preserves: ['No user-visible impact', 'Minor telemetry overhead'],
    canUndo: false,
  },
  'apc-injection-monitor': {
    whatChecked: 'Whether APC (Asynchronous Procedure Call) injection into remote processes is monitored.',
    riskExplanation: 'APC injection is used by malware to execute code inside legitimate processes without creating new threads, evading detection.',
    passDetail: 'APC injection monitoring active. No cross-process APC anomalies detected.',
    fixActionsTemplate: ['Enable ETW APC monitoring', 'Configure Sentinel to alert on cross-process APC queuing'],
    preserves: ['Normal application functionality'],
    canUndo: true,
    undoPath: 'Sentinel → Settings → EDR → Disable APC monitoring',
  },
  'parent-pid-spoofing': {
    whatChecked: 'Whether process creation auditing detects parent PID spoofing (PPID mismatches).',
    riskExplanation: 'Malware spoofs parent PIDs to appear as children of trusted processes (like explorer.exe), bypassing process-tree-based detection.',
    passDetail: 'Process creation auditing active. PPID validation enabled.',
    fixActionsTemplate: ['Enable Process Creation auditing (Event ID 4688)', 'Enable command-line logging in audit policy', 'Configure Sentinel to detect PPID mismatches'],
    preserves: ['Normal process creation', 'Slight audit log volume increase'],
    canUndo: true,
    undoPath: 'Audit Policy → Process Creation → Disable',
  },
  'token-elevation-guard': {
    whatChecked: 'Token privilege escalation monitoring and UAC bypass detection.',
    riskExplanation: 'Token manipulation allows malware to escalate from user to SYSTEM privileges without triggering UAC prompts.',
    passDetail: 'Token elevation monitoring active. No suspicious privilege escalations detected.',
    fixActionsTemplate: ['Enable token audit logging', 'Set UAC to Always Notify', 'Monitor for known UAC bypass techniques'],
    preserves: ['Normal UAC functionality', 'Admin operations unaffected'],
    canUndo: true,
    undoPath: 'UAC Settings → Restore previous level',
  },
  'shadow-stack': {
    whatChecked: 'Hardware-enforced Shadow Stack (CET) status for return address protection.',
    riskExplanation: 'Shadow Stack prevents Return-Oriented Programming (ROP) attacks by maintaining a hardware-protected copy of return addresses.',
    passDetail: 'CET Shadow Stack enabled for compatible applications.',
    fixActionsTemplate: ['Enable CET via Windows Security', 'Apply to critical system processes'],
    preserves: ['Application compatibility', 'Most software unaffected'],
    canUndo: true,
    undoPath: 'Windows Security → Exploit Protection → Disable Shadow Stack',
  },
  'boot-integrity': {
    whatChecked: 'Measured Boot, boot log integrity, and early-launch anti-malware (ELAM) status.',
    riskExplanation: 'Boot-level attacks (bootkits) load before the OS and are invisible to all runtime security tools.',
    passDetail: 'Measured Boot active. ELAM driver loaded. Boot log integrity verified.',
    fixActionsTemplate: ['Enable Measured Boot', 'Verify ELAM driver registration', 'Check boot log for tampering'],
    preserves: ['Boot performance', 'OS startup sequence'],
    canUndo: false,
  },
  'memory-integrity': {
    whatChecked: 'Memory integrity (HVCI) enforcement status and vulnerable driver blocklist.',
    riskExplanation: 'Without memory integrity, kernel-mode code can be modified at runtime, enabling rootkits and kernel exploits.',
    passDetail: 'Memory integrity (HVCI) enabled. Vulnerable driver blocklist active.',
    fixActionsTemplate: ['Enable Memory Integrity in Windows Security', 'Update vulnerable driver blocklist'],
    preserves: ['Most drivers and applications', 'Some older drivers may need updates'],
    canUndo: true,
    undoPath: 'Windows Security → Device Security → Core Isolation → Off',
  },
  'credential-dump-protection': {
    whatChecked: 'Protection against credential dumping: WDigest plaintext storage, LSA protection, Credential Guard.',
    riskExplanation: 'WDigest stores passwords in plaintext in memory. Without protection, any admin process can dump all logged-in credentials.',
    passDetail: 'WDigest plaintext disabled. LSA protection enabled.',
    fixActionsTemplate: ['Disable WDigest UseLogonCredential', 'Enable LSA RunAsPPL', 'Enable Credential Guard'],
    preserves: ['Authentication functionality', 'SSO and domain auth'],
    canUndo: true,
    undoPath: 'Registry → WDigest → UseLogonCredential=1',
  },
};

// ═══════════════════════════════════════════════════════════════
// KERNEL & FIRMWARE — 15 checks
// ═══════════════════════════════════════════════════════════════

export const KERNEL_CHECK_DETAILS: Record<string, CheckDetailTemplate> = {
  'secure-boot': {
    whatChecked: 'UEFI Secure Boot status and key database integrity.',
    riskExplanation: 'Without Secure Boot, bootkits and unsigned bootloaders can load before the OS, compromising the entire trust chain.',
    passDetail: 'Secure Boot enabled. Key database intact.',
    fixActionsTemplate: ['Enable Secure Boot in UEFI/BIOS settings'],
    preserves: ['OS boot process', 'Signed bootloaders'],
    canUndo: true,
    undoPath: 'UEFI/BIOS → Secure Boot → Disable',
  },
  'tpm-status': {
    whatChecked: 'TPM 2.0 presence, ownership, and attestation capability.',
    riskExplanation: 'TPM provides hardware-based key storage and platform integrity measurement. Without it, BitLocker and Credential Guard are weakened.',
    passDetail: 'TPM 2.0 present and owned. Attestation ready.',
    fixActionsTemplate: ['Enable TPM in UEFI/BIOS', 'Take TPM ownership', 'Clear and re-initialize if corrupted'],
    preserves: ['BitLocker keys (backup first!)', 'Windows Hello credentials'],
    canUndo: false,
  },
  'vbs-status': {
    whatChecked: 'Virtualization-Based Security (VBS) status and required features.',
    riskExplanation: 'VBS creates a secure memory enclave that even kernel-level malware cannot access. Required for Credential Guard and HVCI.',
    passDetail: 'VBS running. Secure kernel active.',
    fixActionsTemplate: ['Enable VBS via Group Policy', 'Enable Hyper-V platform feature', 'Verify CPU virtualization support'],
    preserves: ['System performance (minor impact)', 'Hyper-V compatibility'],
    canUndo: true,
    undoPath: 'Group Policy → Device Guard → Disable VBS',
  },
  'driver-signing': {
    whatChecked: 'Driver Signature Enforcement (DSE) status and test-signing mode.',
    riskExplanation: 'Disabled DSE allows unsigned kernel drivers — the primary method for rootkit installation.',
    passDetail: 'DSE enforced. Test-signing mode off.',
    fixActionsTemplate: ['Enable DSE enforcement', 'Disable test-signing mode (bcdedit)', 'Remove unsigned drivers'],
    preserves: ['All signed drivers', 'System stability'],
    canUndo: false,
  },
  'patchguard-status': {
    whatChecked: 'Kernel Patch Protection (PatchGuard/KPP) integrity indicators.',
    riskExplanation: 'PatchGuard prevents kernel structure modification. If bypassed, rootkits can hide processes, files, and network connections.',
    passDetail: 'PatchGuard active. No kernel structure tampering detected.',
    fixActionsTemplate: ['Verify kernel integrity', 'Check for known PatchGuard bypass indicators'],
    preserves: ['System stability', 'Kernel functionality'],
    canUndo: false,
  },
  'elam-status': {
    whatChecked: 'Early Launch Anti-Malware (ELAM) driver registration and boot-time protection.',
    riskExplanation: 'ELAM loads before all other drivers, allowing it to check each driver before it loads. Without it, malicious drivers load freely.',
    passDetail: 'ELAM driver registered and active at boot.',
    fixActionsTemplate: ['Verify ELAM driver registration', 'Enable boot-start driver policy'],
    preserves: ['Boot sequence', 'Driver loading'],
    canUndo: false,
  },
  'kernel-dma-protection': {
    whatChecked: 'DMA (Direct Memory Access) protection status for Thunderbolt/external ports.',
    riskExplanation: 'DMA attacks via Thunderbolt/PCIe can read/write system memory directly, bypassing all software protections.',
    passDetail: 'Kernel DMA Protection enabled.',
    fixActionsTemplate: ['Enable Kernel DMA Protection in BIOS', 'Disable Thunderbolt when not in use'],
    preserves: ['Thunderbolt device functionality', 'External GPU support'],
    canUndo: true,
    undoPath: 'BIOS → Security → DMA Protection → Disable',
  },
  'bitlocker-status': {
    whatChecked: 'BitLocker full-disk encryption status, protection method, and recovery key backup.',
    riskExplanation: 'Without full-disk encryption, anyone with physical access can read all data by booting from USB or removing the drive.',
    passDetail: 'BitLocker enabled on system drive. TPM-based protector active.',
    fixActionsTemplate: ['Enable BitLocker on system drive', 'Use TPM + PIN protector', 'Backup recovery key'],
    preserves: ['Data accessibility', 'Boot performance (minimal impact)'],
    canUndo: true,
    undoPath: 'Control Panel → BitLocker → Decrypt drive',
  },
  'firmware-version': {
    whatChecked: 'UEFI/BIOS firmware version against known vulnerable versions.',
    riskExplanation: 'Outdated firmware may contain exploitable vulnerabilities that persist across OS reinstalls.',
    passDetail: 'Firmware version current. No known vulnerabilities for detected version.',
    fixActionsTemplate: ['Update UEFI/BIOS firmware from manufacturer', 'Verify firmware integrity'],
    preserves: ['System configuration', 'BIOS settings'],
    canUndo: false,
  },
  'hypervisor-enforcement': {
    whatChecked: 'Hypervisor enforcement for code integrity and isolation of security-critical operations.',
    riskExplanation: 'The hypervisor provides the strongest isolation boundary. Without it, kernel exploits can compromise all security features.',
    passDetail: 'Hypervisor running. Security features utilizing hardware isolation.',
    fixActionsTemplate: ['Enable Hyper-V platform', 'Enable hypervisor-enforced code integrity'],
    preserves: ['Virtualization capability', 'System performance'],
    canUndo: true,
    undoPath: 'Windows Features → Disable Hyper-V',
  },
  'wdac-policy': {
    whatChecked: 'Windows Defender Application Control (WDAC) policy status and enforcement level.',
    riskExplanation: 'WDAC prevents unauthorized applications from running. Without it, any downloaded executable can run with user privileges.',
    passDetail: 'WDAC policy active in enforce mode.',
    fixActionsTemplate: ['Create WDAC base policy', 'Deploy in audit mode first', 'Transition to enforce mode'],
    preserves: ['Whitelisted applications', 'System binaries'],
    canUndo: true,
    undoPath: 'Remove WDAC policy file and reboot',
  },
  'system-guard': {
    whatChecked: 'Windows System Guard runtime attestation and Secure Launch status.',
    riskExplanation: 'System Guard provides hardware-rooted boot integrity measurement. Without it, boot-time attacks go undetected.',
    passDetail: 'System Guard active. Secure Launch configured.',
    fixActionsTemplate: ['Enable System Guard Secure Launch', 'Verify hardware support'],
    preserves: ['Boot process', 'System performance'],
    canUndo: true,
    undoPath: 'Group Policy → System Guard → Disable',
  },
  'kernel-cfg': {
    whatChecked: 'Control Flow Guard (CFG) enforcement in kernel mode.',
    riskExplanation: 'Kernel CFG prevents control flow hijacking attacks that redirect execution to attacker-controlled code.',
    passDetail: 'Kernel CFG enabled and enforcing.',
    fixActionsTemplate: ['Enable kernel CFG enforcement', 'Verify with Windows Security'],
    preserves: ['Kernel stability', 'Driver compatibility'],
    canUndo: true,
    undoPath: 'Registry → CFG settings',
  },
  'debug-disabled': {
    whatChecked: 'Kernel debug mode, boot debugger, and remote debugging status.',
    riskExplanation: 'Kernel debugging allows full system memory access. If enabled, an attacker with network access can control the entire system.',
    passDetail: 'Kernel debug disabled. Boot debug off. No remote debugger.',
    fixActionsTemplate: ['Disable kernel debug (bcdedit /debug off)', 'Disable boot debug'],
    preserves: ['Normal system operation', 'Application debugging unchanged'],
    canUndo: true,
    undoPath: 'bcdedit /debug on',
  },
  'spectre-meltdown': {
    whatChecked: 'Spectre/Meltdown microcode mitigations, retpoline status, and branch prediction hardening.',
    riskExplanation: 'Speculative execution vulnerabilities allow cross-process data leakage including passwords and encryption keys.',
    passDetail: 'Spectre/Meltdown mitigations active. Microcode current.',
    fixActionsTemplate: ['Install latest CPU microcode update', 'Enable OS mitigations via registry', 'Update BIOS'],
    preserves: ['System performance (minor impact)', 'Application compatibility'],
    canUndo: true,
    undoPath: 'Registry → FeatureSettingsOverride → Disable mitigations',
  },
  'cpu-microcode': {
    whatChecked: 'CPU microcode revision and firmware update status.',
    riskExplanation: 'Outdated microcode leaves speculative execution and other CPU bugs unpatched, enabling side-channel attacks.',
    passDetail: 'CPU microcode revision present. Firmware up to date.',
    fixActionsTemplate: ['Update BIOS/UEFI firmware from manufacturer', 'Install Windows microcode updates'],
    preserves: ['CPU functionality', 'System stability'],
    canUndo: false,
  },
  'dkom-detection': {
    whatChecked: 'Direct Kernel Object Manipulation detection — compares WMI and PowerShell process counts.',
    riskExplanation: 'DKOM allows rootkits to hide processes by unlinking them from kernel structures. Hidden processes can steal data or mine crypto undetected.',
    passDetail: 'Process counts consistent between WMI and PowerShell. No hidden processes detected.',
    fixActionsTemplate: ['Run offline antimalware scan', 'Check for rootkit indicators', 'Verify kernel integrity with sfc'],
    preserves: ['Running processes', 'System stability'],
    canUndo: false,
  },
  'vulnerable-driver-blocklist': {
    whatChecked: 'Installed kernel drivers against the Microsoft Vulnerable Driver Blocklist.',
    riskExplanation: 'Known vulnerable drivers can be exploited by attackers to gain kernel-level access (Bring Your Own Vulnerable Driver attacks).',
    passDetail: 'No known vulnerable drivers detected. Blocklist active.',
    fixActionsTemplate: ['Enable vulnerable driver blocklist', 'Remove identified vulnerable drivers', 'Update affected drivers'],
    preserves: ['Hardware functionality', 'Driver compatibility'],
    canUndo: false,
  },
  'unsigned-driver-audit': {
    whatChecked: 'Running kernel drivers for valid digital signatures.',
    riskExplanation: 'Unsigned drivers bypass code integrity verification and can contain malicious code that runs at kernel level.',
    passDetail: 'All running kernel drivers are digitally signed.',
    fixActionsTemplate: ['Identify and remove unsigned drivers', 'Enforce driver signature enforcement', 'Update unsigned drivers to signed versions'],
    preserves: ['Signed drivers', 'System stability'],
    canUndo: false,
  },
  'privilege-escalation-hardening': {
    whatChecked: 'UAC configuration, AlwaysInstallElevated policy, and privilege escalation vectors.',
    riskExplanation: 'Weak UAC settings and AlwaysInstallElevated allow standard users to gain admin privileges through malicious installers or exploits.',
    passDetail: 'UAC hardened. AlwaysInstallElevated disabled. No privilege escalation vectors detected.',
    fixActionsTemplate: ['Set UAC to maximum level', 'Disable AlwaysInstallElevated', 'Enable FilterAdministratorToken'],
    preserves: ['Application installation (with UAC prompt)', 'Admin functionality'],
    canUndo: true,
    undoPath: 'Registry → Policies\\System → Reset UAC to defaults',
  },
  'kernel-file-integrity': {
    whatChecked: 'Critical kernel files (ntoskrnl.exe, hal.dll, ci.dll) for valid digital signatures.',
    riskExplanation: 'Modified kernel files indicate a rootkit or advanced persistent threat has compromised the OS at the deepest level.',
    passDetail: 'All critical kernel files have valid signatures.',
    fixActionsTemplate: ['Run sfc /scannow to repair corrupted files', 'Run DISM /RestoreHealth', 'Boot from recovery and repair'],
    preserves: ['System functionality', 'Boot process'],
    canUndo: false,
  },
  'kernel-driver-paths': {
    whatChecked: 'Kernel driver loading paths — flags drivers loaded from non-standard system directories.',
    riskExplanation: 'Legitimate kernel drivers load from System32\\drivers. Drivers from other paths may be malicious rootkits or unauthorized software.',
    passDetail: 'All kernel drivers loaded from standard system paths.',
    fixActionsTemplate: ['Investigate non-system path drivers', 'Remove suspicious drivers', 'Verify driver signatures'],
    preserves: ['Legitimate drivers', 'Hardware functionality'],
    canUndo: false,
  },
};

// ═══════════════════════════════════════════════════════════════
// EDR — Additional check templates (5 missing)
// ═══════════════════════════════════════════════════════════════

export const EDR_CHECK_DETAILS_EXTRA: Record<string, CheckDetailTemplate> = {
  'com-hijacking': {
    whatChecked: 'User-level COM CLSID entries for potential COM object hijacking persistence.',
    riskExplanation: 'COM hijacking allows malware to intercept legitimate COM calls, executing malicious code whenever an application uses the hijacked COM object.',
    passDetail: 'User-level CLSID count within normal range. No suspicious COM registrations.',
    fixActionsTemplate: ['Audit user CLSIDs in HKCU\\SOFTWARE\\Classes\\CLSID', 'Remove suspicious COM registrations', 'Monitor for new user COM entries'],
    preserves: ['Application COM functionality', 'System COM objects'],
    canUndo: false,
  },
  'sandbox-capabilities': {
    whatChecked: 'Network Protection status and Windows Sandbox availability.',
    riskExplanation: 'Without sandbox capabilities, malicious files and scripts execute in the full user context with access to all data and network resources.',
    passDetail: 'Network Protection enabled. Sandbox available for isolated execution.',
    fixActionsTemplate: ['Enable Network Protection', 'Install Windows Sandbox feature', 'Enable application guard'],
    preserves: ['Network connectivity', 'Application access'],
    canUndo: true,
    undoPath: 'Set-MpPreference -EnableNetworkProtection 0',
  },
  'behavior-analysis': {
    whatChecked: 'Running processes for anomalous behavior: unsigned executables consuming high CPU/memory resources.',
    riskExplanation: 'Cryptominers and data exfiltration tools often run as unsigned processes with abnormally high resource usage.',
    passDetail: 'No unsigned high-resource processes detected.',
    fixActionsTemplate: ['Enable PUA Protection in Defender', 'Enable Network Protection', 'Investigate flagged processes'],
    preserves: ['Legitimate applications', 'System performance'],
    canUndo: false,
  },
  'critical-file-protection': {
    whatChecked: 'ACLs on critical system files (hosts, drivers, boot config) for user-writable permissions.',
    riskExplanation: 'If standard users can write to critical system files, malware running at user level can redirect DNS, install rootkits, or modify boot configuration.',
    passDetail: 'Critical system files properly protected. No user-writable vulnerabilities.',
    fixActionsTemplate: ['Reset ACLs on critical files', 'Remove user write permissions', 'Enable file integrity monitoring'],
    preserves: ['File accessibility for admins', 'System functionality'],
    canUndo: false,
  },
  'handle-monitor': {
    whatChecked: 'Handle count on LSASS process — abnormally high counts indicate credential dumping tools.',
    riskExplanation: 'Tools like Mimikatz open many handles to LSASS to dump credentials. High handle counts are a strong indicator of active credential theft.',
    passDetail: 'LSASS handle count within normal range. No credential dumping indicators.',
    fixActionsTemplate: ['Enable LSASS PPL protection', 'Enable ASR rule for credential stealing', 'Investigate high handle count'],
    preserves: ['Authentication functionality', 'System login'],
    canUndo: false,
  },
};

// ═══════════════════════════════════════════════════════════════
// PERFORMANCE — 25 checks
// ═══════════════════════════════════════════════════════════════

export const PERFORMANCE_CHECK_DETAILS: Record<string, CheckDetailTemplate> = {
  'dpc-latency': {
    whatChecked: 'Deferred Procedure Call (DPC) latency — measures interrupt handling delay.',
    riskExplanation: 'High DPC latency causes audio glitches, USB dropouts, and laggy input. Usually caused by bad drivers.',
    passDetail: 'DPC latency within acceptable range (<500µs average).',
    fixActionsTemplate: ['Identify high-latency drivers', 'Update or disable problematic drivers', 'Disable power-saving on USB controllers'],
    preserves: ['Audio quality', 'USB device responsiveness'],
    canUndo: true,
    undoPath: 'Re-enable disabled drivers',
  },
  'timer-resolution': {
    whatChecked: 'System timer resolution and multimedia timer precision.',
    riskExplanation: 'Default 15.6ms timer resolution causes scheduling jitter. Applications requiring precise timing perform poorly.',
    passDetail: 'Timer resolution set to high precision (1ms or better).',
    fixActionsTemplate: ['Set global timer resolution to 1ms', 'Verify multimedia timer service'],
    preserves: ['Battery life may decrease slightly', 'System stability'],
    canUndo: true,
    undoPath: 'Reset timer resolution to default 15.6ms',
  },
  'core-parking': {
    whatChecked: 'CPU core parking configuration and power plan core utilization settings.',
    riskExplanation: 'Aggressive core parking disables CPU cores to save power, causing stuttering under bursty workloads.',
    passDetail: 'Core parking optimized for responsiveness. All cores available.',
    fixActionsTemplate: ['Set minimum cores to 100%', 'Adjust power plan for performance', 'Disable core parking via registry'],
    preserves: ['Power efficiency mode still available', 'Thermal management'],
    canUndo: true,
    undoPath: 'Power Plan → Restore balanced settings',
  },
  'memory-compression': {
    whatChecked: 'Windows Memory Compression status and impact on system responsiveness.',
    riskExplanation: 'Memory compression trades CPU cycles for RAM capacity. On systems with adequate RAM, it wastes CPU unnecessarily.',
    passDetail: 'Memory compression configured appropriately for available RAM.',
    fixActionsTemplate: ['Adjust memory compression based on RAM availability', 'Disable if RAM > 16GB'],
    preserves: ['System stability', 'Application memory access'],
    canUndo: true,
    undoPath: 'Enable-MMAgent -MemoryCompression',
  },
  'power-plan': {
    whatChecked: 'Active Windows power plan and processor power management settings.',
    riskExplanation: 'Balanced/Power Saver plans throttle CPU frequency, causing inconsistent performance under load.',
    passDetail: 'High Performance or Ultimate Performance power plan active.',
    fixActionsTemplate: ['Switch to High Performance plan', 'Set minimum processor state to 100%', 'Disable processor idle'],
    preserves: ['Battery life (reduced on laptops)', 'Thermal headroom'],
    canUndo: true,
    undoPath: 'Power Options → Switch to Balanced',
  },
  'startup-impact': {
    whatChecked: 'Boot time, number of startup programs, and their cumulative impact.',
    riskExplanation: 'Excessive startup programs slow boot time and consume resources before the user can even interact with the system.',
    passDetail: 'Startup programs within acceptable limits. Boot time optimized.',
    fixActionsTemplate: ['Disable non-essential startup programs', 'Defer startup of heavy applications'],
    preserves: ['Essential startup applications', 'Security software auto-start'],
    canUndo: true,
    undoPath: 'Task Manager → Startup → Re-enable programs',
  },
  'visual-effects': {
    whatChecked: 'Windows visual effects settings and their GPU/CPU impact.',
    riskExplanation: 'Excessive visual effects waste GPU cycles and increase memory usage without functional benefit.',
    passDetail: 'Visual effects optimized for performance.',
    fixActionsTemplate: ['Set visual effects to "Adjust for best performance"', 'Keep only essential effects'],
    preserves: ['Desktop usability', 'Font smoothing'],
    canUndo: true,
    undoPath: 'System Properties → Advanced → Visual Effects → Best appearance',
  },
  'disk-queue': {
    whatChecked: 'Disk I/O queue depth, pending operations, and throughput bottlenecks.',
    riskExplanation: 'High disk queue lengths indicate storage bottleneck — applications wait for I/O, causing system-wide slowdown.',
    passDetail: 'Disk queue lengths normal. No I/O bottleneck detected.',
    fixActionsTemplate: ['Identify high-I/O processes', 'Optimize indexing service', 'Consider SSD upgrade for HDD'],
    preserves: ['Data integrity', 'File system operations'],
    canUndo: false,
  },
  'pagefile-config': {
    whatChecked: 'Virtual memory (pagefile) configuration, size, and placement.',
    riskExplanation: 'Incorrect pagefile configuration causes excessive paging, application crashes (out of memory), or wasted disk space.',
    passDetail: 'Pagefile properly sized on fastest drive.',
    fixActionsTemplate: ['Set pagefile to 1.5x RAM size', 'Place on fastest SSD', 'Disable pagefile on HDD'],
    preserves: ['Application stability', 'System memory management'],
    canUndo: true,
    undoPath: 'System Properties → Advanced → Virtual Memory → System managed',
  },
  'indexing-service': {
    whatChecked: 'Windows Search indexing service scope and resource consumption.',
    riskExplanation: 'Broad indexing scope causes constant background disk I/O, especially on HDDs. Wastes resources indexing files you never search.',
    passDetail: 'Indexing restricted to essential locations.',
    fixActionsTemplate: ['Restrict indexing to user folders only', 'Exclude build and temp directories', 'Disable content indexing on SSDs'],
    preserves: ['Windows Search functionality', 'Start menu search'],
    canUndo: true,
    undoPath: 'Indexing Options → Add locations back',
  },
  'superfetch-prefetch': {
    whatChecked: 'SysMain (Superfetch) and Prefetch configuration for optimal application launch.',
    riskExplanation: 'On SSDs, Superfetch provides minimal benefit while consuming memory. On HDDs, it significantly improves launch times.',
    passDetail: 'SysMain configured appropriately for storage type.',
    fixActionsTemplate: ['Configure SysMain based on primary storage type', 'Disable on NVMe/SSD if RAM < 16GB'],
    preserves: ['Application launch times', 'System stability'],
    canUndo: true,
    undoPath: 'Services → SysMain → Automatic',
  },
  'network-throttling': {
    whatChecked: 'Network throttling index, Nagle algorithm, TCP auto-tuning, and receive window size.',
    riskExplanation: 'Default network settings prioritize power saving over throughput, reducing network performance.',
    passDetail: 'Network throttling disabled. TCP auto-tuning optimized.',
    fixActionsTemplate: ['Disable network throttling index', 'Optimize TCP auto-tuning level', 'Disable Nagle for low-latency'],
    preserves: ['Network stability', 'Connection reliability'],
    canUndo: true,
    undoPath: 'Registry → NetworkThrottlingIndex → Restore default',
  },
  'gpu-scheduling': {
    whatChecked: 'Hardware-accelerated GPU scheduling (HAGS) status and driver support.',
    riskExplanation: 'HAGS reduces CPU overhead for GPU task scheduling, improving frame times in games and GPU-accelerated workloads.',
    passDetail: 'Hardware GPU scheduling enabled (if supported).',
    fixActionsTemplate: ['Enable HAGS in Display Settings', 'Update GPU drivers'],
    preserves: ['Display output', 'Application compatibility'],
    canUndo: true,
    undoPath: 'Display Settings → Graphics → Disable HAGS',
  },
  'thread-affinity': {
    whatChecked: 'CPU topology awareness: physical cores, logical threads, NUMA nodes, and CCX/CCD layout.',
    riskExplanation: 'Incorrect thread scheduling across CCX/CCD boundaries (AMD) or P/E cores (Intel) causes cache thrashing and latency spikes.',
    passDetail: 'CPU topology correctly detected. Thread scheduling optimized.',
    fixActionsTemplate: ['Configure preferred cores', 'Set process affinity for latency-sensitive apps'],
    preserves: ['Multi-threaded workloads', 'Background processing'],
    canUndo: true,
    undoPath: 'Reset process affinity to default',
  },
  'game-mode': {
    whatChecked: 'Windows Game Mode, Game Bar, and game-related optimization settings.',
    riskExplanation: 'Game Mode reduces background activity during gaming. Game Bar overlay can cause FPS drops in some games.',
    passDetail: 'Game Mode configured. Game Bar impact minimized.',
    fixActionsTemplate: ['Enable Game Mode', 'Disable Game Bar if causing issues', 'Disable captures'],
    preserves: ['Game functionality', 'Streaming capability'],
    canUndo: true,
    undoPath: 'Windows Settings → Gaming → Restore defaults',
  },
  'disk-write-cache': {
    whatChecked: 'Disk write-cache policy on the primary storage device (SSD/HDD).',
    riskExplanation: 'Disabled write cache on HDDs significantly reduces write performance. On SSDs it has less impact but still helps with burst writes. Power loss with write cache enabled can cause data loss on HDDs without battery backup.',
    passDetail: 'Disk write-cache enabled or SSD/NVMe detected (cache less critical).',
    fixActionsTemplate: ['Enable disk write-cache on primary drive', 'Verify UPS/battery backup for data safety'],
    preserves: ['Data integrity (ensure UPS if on HDD)', 'Read performance unchanged'],
    canUndo: true,
    undoPath: 'Device Manager → Disk drives → Properties → Policies → Disable write cache',
  },
  'cpu-topology': {
    whatChecked: 'CPU core and thread topology — physical cores, logical threads, SMT/HT status.',
    riskExplanation: 'Incorrect core count detection can lead to suboptimal thread scheduling and reduced performance in multi-threaded workloads.',
    passDetail: 'CPU topology correctly detected. All cores and threads active.',
    fixActionsTemplate: ['Verify SMT/HT enabled in BIOS', 'Check for disabled cores'],
    preserves: ['CPU functionality', 'System stability'],
    canUndo: false,
  },
  'interrupt-steering': {
    whatChecked: 'Interrupt affinity and RSS (Receive Side Scaling) distribution across CPU cores.',
    riskExplanation: 'Poor interrupt distribution concentrates all network/USB interrupts on a single core, causing latency spikes and dropped packets.',
    passDetail: 'Interrupts distributed across multiple cores.',
    fixActionsTemplate: ['Enable RSS on network adapters', 'Configure interrupt affinity via device manager'],
    preserves: ['Network throughput', 'Device functionality'],
    canUndo: true,
    undoPath: 'Reset network adapter RSS settings to defaults',
  },
  'large-pages': {
    whatChecked: 'Large Pages (2MB) support and SeLockMemoryPrivilege assignment.',
    riskExplanation: 'Large pages reduce TLB misses for memory-intensive applications, improving performance by 5-30% for databases and VMs.',
    passDetail: 'Large pages supported. SeLockMemoryPrivilege assigned.',
    fixActionsTemplate: ['Grant SeLockMemoryPrivilege to current user', 'Restart applications to use large pages'],
    preserves: ['System memory management', 'Application compatibility'],
    canUndo: true,
    undoPath: 'Remove SeLockMemoryPrivilege from user account',
  },
  'vram-status': {
    whatChecked: 'GPU model, VRAM capacity, and driver version.',
    riskExplanation: 'Insufficient VRAM causes texture streaming stutters and GPU memory paging which severely impacts graphical performance.',
    passDetail: 'GPU detected with adequate VRAM.',
    fixActionsTemplate: ['Update GPU drivers', 'Reduce texture quality if VRAM limited'],
    preserves: ['Display output', 'Current resolution settings'],
    canUndo: false,
  },
  'standby-list': {
    whatChecked: 'Available physical RAM and standby list pressure.',
    riskExplanation: 'When free RAM drops below 5%, Windows aggressively pages to disk causing system-wide stuttering and application hangs.',
    passDetail: 'Adequate free RAM available. Standby list healthy.',
    fixActionsTemplate: ['Close memory-heavy applications', 'Flush standby list', 'Increase pagefile size'],
    preserves: ['Running applications', 'System stability'],
    canUndo: false,
  },
  'io-priority': {
    whatChecked: 'Background I/O activity from Windows Update and BITS services.',
    riskExplanation: 'Active Windows Update downloads consume disk I/O bandwidth, causing delays for user applications especially on HDDs.',
    passDetail: 'Background I/O services idle. No disk bandwidth contention.',
    fixActionsTemplate: ['Pause Windows Update downloads', 'Set BITS to low priority', 'Schedule updates for off-hours'],
    preserves: ['Update functionality', 'System security patches'],
    canUndo: true,
    undoPath: 'Resume Windows Update services',
  },
  'ntfs-health': {
    whatChecked: 'NTFS volume health, MFT fragmentation, and free space on system drive.',
    riskExplanation: 'A degraded NTFS volume with low free space causes exponentially slower file operations and risks data corruption.',
    passDetail: 'NTFS volume healthy. Adequate free space.',
    fixActionsTemplate: ['Run chkdsk /scan', 'Free disk space', 'Defragment MFT (HDD only)'],
    preserves: ['File system integrity', 'Stored data'],
    canUndo: false,
  },
  'winsxs-store': {
    whatChecked: 'Windows Component Store (WinSxS) size and cleanup potential.',
    riskExplanation: 'An oversized WinSxS folder (>15GB) wastes disk space and can slow servicing operations like Windows Update.',
    passDetail: 'WinSxS component store within acceptable size.',
    fixActionsTemplate: ['Run DISM /StartComponentCleanup', 'Remove superseded updates', 'Clear temporary files'],
    preserves: ['Installed components', 'Rollback capability (for recent updates)'],
    canUndo: false,
  },
  'registry-size': {
    whatChecked: 'Registry hive sizes (HKLM + HKCU) and key count.',
    riskExplanation: 'A bloated registry with thousands of orphaned keys slows boot time, login, and application startup.',
    passDetail: 'Registry size within normal range.',
    fixActionsTemplate: ['Clean orphaned registry keys', 'Remove leftover uninstall entries'],
    preserves: ['Installed software settings', 'System configuration'],
    canUndo: false,
  },
  'context-switches': {
    whatChecked: 'CPU context switch rate — measures thread scheduling overhead.',
    riskExplanation: 'Extremely high context switch rates (>100k/s) indicate thread contention, causing CPU overhead and reduced application throughput.',
    passDetail: 'Context switch rate within normal range.',
    fixActionsTemplate: ['Identify high-thread-count processes', 'Reduce unnecessary background services'],
    preserves: ['Running applications', 'System responsiveness'],
    canUndo: false,
  },
  'ram-stability': {
    whatChecked: 'RAM capacity, speed, dual-channel status, and hardware error history.',
    riskExplanation: 'Faulty or mismatched RAM causes blue screens, data corruption, and intermittent application crashes that are hard to diagnose.',
    passDetail: 'RAM configuration healthy. No hardware errors detected.',
    fixActionsTemplate: ['Run Windows Memory Diagnostic', 'Check for mismatched RAM modules', 'Verify XMP/DOCP profile'],
    preserves: ['System stability', 'Stored data'],
    canUndo: false,
  },
  'thermal-status': {
    whatChecked: 'CPU and system thermal zone temperatures and critical thresholds.',
    riskExplanation: 'High temperatures cause thermal throttling (reduced CPU speed), shortened hardware lifespan, and potential system shutdowns.',
    passDetail: 'Temperatures within safe operating range.',
    fixActionsTemplate: ['Clean CPU cooler and case fans', 'Reapply thermal paste', 'Improve case airflow'],
    preserves: ['Hardware longevity', 'System performance'],
    canUndo: false,
  },
};
