/**
 * SENTINEL — Deutsche Kernel & Firmware Scan-Check-Beschreibungen (15 Prüfungen)
 */
import type { CheckDetailTemplate } from './networkScanChecks';

export const KERNEL_CHECK_DETAILS_DE: Record<string, CheckDetailTemplate> = {
  'secure-boot': {
    whatChecked: 'UEFI Secure Boot Status und Schlüsseldatenbank-Integrität.',
    riskExplanation: 'Ohne Secure Boot können Bootkits und unsignierte Bootloader vor dem Betriebssystem laden und die gesamte Vertrauenskette kompromittieren.',
    passDetail: 'Secure Boot aktiviert. Schlüsseldatenbank intakt.',
    fixActionsTemplate: ['Secure Boot in UEFI/BIOS-Einstellungen aktivieren'],
    preserves: ['OS-Boot-Prozess', 'Signierte Bootloader'],
    canUndo: true,
    undoPath: 'UEFI/BIOS → Secure Boot → Deaktivieren',
  },
  'tpm-status': {
    whatChecked: 'TPM 2.0 Vorhandensein, Besitz und Attestierungsfähigkeit.',
    riskExplanation: 'TPM bietet hardware-basierte Schlüsselspeicherung und Plattform-Integritätsmessung. Ohne TPM sind BitLocker und Credential Guard geschwächt.',
    passDetail: 'TPM 2.0 vorhanden und im Besitz. Attestierung bereit.',
    fixActionsTemplate: ['TPM in UEFI/BIOS aktivieren', 'TPM-Besitz übernehmen', 'Bei Korruption TPM löschen und neu initialisieren'],
    preserves: ['BitLocker-Schlüssel (vorher sichern!)', 'Windows Hello-Zugangsdaten'],
    canUndo: false,
  },
  'vbs-status': {
    whatChecked: 'Virtualisierungsbasierte Sicherheit (VBS) Status und benötigte Features.',
    riskExplanation: 'VBS erstellt eine sichere Speicher-Enklave, auf die selbst Kernel-Level-Malware nicht zugreifen kann. Benötigt für Credential Guard und HVCI.',
    passDetail: 'VBS läuft. Sicherer Kernel aktiv.',
    fixActionsTemplate: ['VBS über Gruppenrichtlinie aktivieren', 'Hyper-V-Plattform-Feature aktivieren', 'CPU-Virtualisierungsunterstützung verifizieren'],
    preserves: ['Systemleistung (geringe Auswirkung)', 'Hyper-V-Kompatibilität'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinie → Device Guard → VBS deaktivieren',
  },
  'driver-signing': {
    whatChecked: 'Treibersignatur-Erzwingung (DSE) Status und Test-Signing-Modus.',
    riskExplanation: 'Deaktivierte DSE erlaubt unsignierte Kernel-Treiber — die primäre Methode für Rootkit-Installation.',
    passDetail: 'DSE erzwungen. Test-Signing-Modus aus.',
    fixActionsTemplate: ['DSE-Erzwingung aktivieren', 'Test-Signing-Modus deaktivieren (bcdedit)', 'Unsignierte Treiber entfernen'],
    preserves: ['Alle signierten Treiber', 'Systemstabilität'],
    canUndo: false,
  },
  'patchguard-status': {
    whatChecked: 'Kernel Patch Protection (PatchGuard/KPP) Integritätsindikatoren.',
    riskExplanation: 'PatchGuard verhindert Kernel-Strukturmodifikation. Bei Umgehung können Rootkits Prozesse, Dateien und Netzwerkverbindungen verbergen.',
    passDetail: 'PatchGuard aktiv. Keine Kernel-Strukturmanipulation erkannt.',
    fixActionsTemplate: ['Kernel-Integrität verifizieren', 'Auf bekannte PatchGuard-Bypass-Indikatoren prüfen'],
    preserves: ['Systemstabilität', 'Kernel-Funktionalität'],
    canUndo: false,
  },
  'elam-status': {
    whatChecked: 'Early Launch Anti-Malware (ELAM) Treiberregistrierung und Boot-Zeit-Schutz.',
    riskExplanation: 'ELAM lädt vor allen anderen Treibern und kann jeden Treiber vor dem Laden prüfen. Ohne ELAM laden bösartige Treiber ungehindert.',
    passDetail: 'ELAM-Treiber registriert und beim Boot aktiv.',
    fixActionsTemplate: ['ELAM-Treiberregistrierung verifizieren', 'Boot-Start-Treiber-Richtlinie aktivieren'],
    preserves: ['Boot-Sequenz', 'Treiber-Laden'],
    canUndo: false,
  },
  'kernel-dma-protection': {
    whatChecked: 'DMA (Direct Memory Access) Schutzstatus für Thunderbolt/externe Ports.',
    riskExplanation: 'DMA-Angriffe über Thunderbolt/PCIe können Systemspeicher direkt lesen/schreiben und alle Software-Schutzmaßnahmen umgehen.',
    passDetail: 'Kernel-DMA-Schutz aktiviert.',
    fixActionsTemplate: ['Kernel-DMA-Schutz im BIOS aktivieren', 'Thunderbolt deaktivieren wenn nicht in Verwendung'],
    preserves: ['Thunderbolt-Gerätefunktionalität', 'Externe GPU-Unterstützung'],
    canUndo: true,
    undoPath: 'BIOS → Sicherheit → DMA-Schutz → Deaktivieren',
  },
  'bitlocker-status': {
    whatChecked: 'BitLocker Festplattenverschlüsselungsstatus, Schutzmethode und Wiederherstellungsschlüssel-Backup.',
    riskExplanation: 'Ohne Festplattenverschlüsselung kann jeder mit physischem Zugang alle Daten lesen — durch Booten von USB oder Entfernen der Festplatte.',
    passDetail: 'BitLocker auf Systemlaufwerk aktiviert. TPM-basierter Schutz aktiv.',
    fixActionsTemplate: ['BitLocker auf Systemlaufwerk aktivieren', 'TPM + PIN-Schutz verwenden', 'Wiederherstellungsschlüssel sichern'],
    preserves: ['Datenzugänglichkeit', 'Boot-Leistung (minimale Auswirkung)'],
    canUndo: true,
    undoPath: 'Systemsteuerung → BitLocker → Laufwerk entschlüsseln',
  },
  'firmware-version': {
    whatChecked: 'UEFI/BIOS-Firmware-Version gegen bekannte verwundbare Versionen.',
    riskExplanation: 'Veraltete Firmware kann ausnutzbare Schwachstellen enthalten, die über OS-Neuinstallationen hinweg bestehen.',
    passDetail: 'Firmware-Version aktuell. Keine bekannten Schwachstellen für erkannte Version.',
    fixActionsTemplate: ['UEFI/BIOS-Firmware vom Hersteller aktualisieren', 'Firmware-Integrität verifizieren'],
    preserves: ['Systemkonfiguration', 'BIOS-Einstellungen'],
    canUndo: false,
  },
  'hypervisor-enforcement': {
    whatChecked: 'Hypervisor-Erzwingung für Code-Integrität und Isolation sicherheitskritischer Operationen.',
    riskExplanation: 'Der Hypervisor bietet die stärkste Isolationsgrenze. Ohne ihn können Kernel-Exploits alle Sicherheitsfeatures kompromittieren.',
    passDetail: 'Hypervisor läuft. Sicherheitsfeatures nutzen Hardware-Isolation.',
    fixActionsTemplate: ['Hyper-V-Plattform aktivieren', 'Hypervisor-erzwungene Code-Integrität aktivieren'],
    preserves: ['Virtualisierungsfähigkeit', 'Systemleistung'],
    canUndo: true,
    undoPath: 'Windows-Features → Hyper-V deaktivieren',
  },
  'wdac-policy': {
    whatChecked: 'Windows Defender Application Control (WDAC) Richtlinienstatus und Erzwingungsstufe.',
    riskExplanation: 'WDAC verhindert die Ausführung unautorisierter Anwendungen. Ohne WDAC kann jede heruntergeladene Executable mit Benutzerrechten laufen.',
    passDetail: 'WDAC-Richtlinie im Erzwingungsmodus aktiv.',
    fixActionsTemplate: ['WDAC-Basisrichtlinie erstellen', 'Zuerst im Audit-Modus bereitstellen', 'In Erzwingungsmodus überführen'],
    preserves: ['Whitelisted Anwendungen', 'System-Binärdateien'],
    canUndo: true,
    undoPath: 'WDAC-Richtliniendatei entfernen und neustarten',
  },
  'system-guard': {
    whatChecked: 'Windows System Guard Laufzeit-Attestierung und Secure Launch Status.',
    riskExplanation: 'System Guard bietet hardware-verwurzelte Boot-Integritätsmessung. Ohne sie bleiben Boot-Zeit-Angriffe unerkannt.',
    passDetail: 'System Guard aktiv. Secure Launch konfiguriert.',
    fixActionsTemplate: ['System Guard Secure Launch aktivieren', 'Hardware-Unterstützung verifizieren'],
    preserves: ['Boot-Prozess', 'Systemleistung'],
    canUndo: true,
    undoPath: 'Gruppenrichtlinie → System Guard → Deaktivieren',
  },
  'kernel-cfg': {
    whatChecked: 'Control Flow Guard (CFG) Erzwingung im Kernel-Modus.',
    riskExplanation: 'Kernel-CFG verhindert Kontrollfluss-Hijacking-Angriffe, die die Ausführung zu Angreifer-kontrolliertem Code umleiten.',
    passDetail: 'Kernel-CFG aktiviert und erzwingend.',
    fixActionsTemplate: ['Kernel-CFG-Erzwingung aktivieren', 'Mit Windows-Sicherheit verifizieren'],
    preserves: ['Kernel-Stabilität', 'Treiber-Kompatibilität'],
    canUndo: true,
    undoPath: 'Registry → CFG-Einstellungen',
  },
  'debug-disabled': {
    whatChecked: 'Kernel-Debug-Modus, Boot-Debugger und Remote-Debugging-Status.',
    riskExplanation: 'Kernel-Debugging ermöglicht vollen Systemspeicherzugriff. Wenn aktiviert, kann ein Angreifer mit Netzwerkzugang das gesamte System kontrollieren.',
    passDetail: 'Kernel-Debug deaktiviert. Boot-Debug aus. Kein Remote-Debugger.',
    fixActionsTemplate: ['Kernel-Debug deaktivieren (bcdedit /debug off)', 'Boot-Debug deaktivieren'],
    preserves: ['Normaler Systembetrieb', 'Anwendungs-Debugging unverändert'],
    canUndo: true,
    undoPath: 'bcdedit /debug on',
  },
  'spectre-meltdown': {
    whatChecked: 'Spectre/Meltdown Microcode-Mitigationen, Retpoline-Status und Branch-Prediction-Härtung.',
    riskExplanation: 'Spekulative Ausführungsschwachstellen ermöglichen prozessübergreifenden Datenleak einschließlich Passwörtern und Verschlüsselungsschlüsseln.',
    passDetail: 'Spectre/Meltdown-Mitigationen aktiv. Microcode aktuell.',
    fixActionsTemplate: ['Neuestes CPU-Microcode-Update installieren', 'OS-Mitigationen über Registry aktivieren', 'BIOS aktualisieren'],
    preserves: ['Systemleistung (geringe Auswirkung)', 'Anwendungskompatibilität'],
    canUndo: true,
    undoPath: 'Registry → FeatureSettingsOverride → Mitigationen deaktivieren',
  },
  'cpu-microcode': {
    whatChecked: 'CPU-Microcode-Revision und Firmware-Update-Status.',
    riskExplanation: 'Veralteter Microcode lässt spekulative Ausführungs- und andere CPU-Bugs ungepatcht — Seitenkanalangriffe werden ermöglicht.',
    passDetail: 'CPU-Microcode-Revision vorhanden. Firmware aktuell.',
    fixActionsTemplate: ['BIOS/UEFI-Firmware vom Hersteller aktualisieren', 'Windows-Microcode-Updates installieren'],
    preserves: ['CPU-Funktionalität', 'Systemstabilität'],
    canUndo: false,
  },
  'dkom-detection': {
    whatChecked: 'Direct Kernel Object Manipulation Erkennung — vergleicht WMI- und PowerShell-Prozesszählungen.',
    riskExplanation: 'DKOM ermöglicht Rootkits, Prozesse zu verstecken, indem sie aus Kernel-Strukturen entfernt werden. Versteckte Prozesse können unerkannt Daten stehlen.',
    passDetail: 'Prozesszählungen zwischen WMI und PowerShell konsistent. Keine versteckten Prozesse.',
    fixActionsTemplate: ['Offline-Antimalware-Scan ausführen', 'Auf Rootkit-Indikatoren prüfen', 'Kernel-Integrität mit sfc verifizieren'],
    preserves: ['Laufende Prozesse', 'Systemstabilität'],
    canUndo: false,
  },
  'vulnerable-driver-blocklist': {
    whatChecked: 'Installierte Kernel-Treiber gegen die Microsoft Vulnerable Driver Blocklist.',
    riskExplanation: 'Bekannte verwundbare Treiber können von Angreifern ausgenutzt werden, um Kernel-Level-Zugriff zu erlangen (BYOVD-Angriffe).',
    passDetail: 'Keine bekannten verwundbaren Treiber erkannt. Blocklist aktiv.',
    fixActionsTemplate: ['Vulnerable Driver Blocklist aktivieren', 'Identifizierte verwundbare Treiber entfernen', 'Betroffene Treiber aktualisieren'],
    preserves: ['Hardware-Funktionalität', 'Treiberkompatibilität'],
    canUndo: false,
  },
  'unsigned-driver-audit': {
    whatChecked: 'Laufende Kernel-Treiber auf gültige digitale Signaturen.',
    riskExplanation: 'Unsignierte Treiber umgehen die Code-Integritätsprüfung und können schädlichen Code auf Kernel-Ebene enthalten.',
    passDetail: 'Alle laufenden Kernel-Treiber sind digital signiert.',
    fixActionsTemplate: ['Unsignierte Treiber identifizieren und entfernen', 'Treibersignaturerzwingung aktivieren', 'Unsignierte Treiber auf signierte Versionen aktualisieren'],
    preserves: ['Signierte Treiber', 'Systemstabilität'],
    canUndo: false,
  },
  'privilege-escalation-hardening': {
    whatChecked: 'UAC-Konfiguration, AlwaysInstallElevated-Richtlinie und Privilege-Escalation-Vektoren.',
    riskExplanation: 'Schwache UAC-Einstellungen und AlwaysInstallElevated erlauben Standardbenutzern, Admin-Rechte über bösartige Installer zu erlangen.',
    passDetail: 'UAC gehärtet. AlwaysInstallElevated deaktiviert. Keine Privilege-Escalation-Vektoren.',
    fixActionsTemplate: ['UAC auf maximale Stufe setzen', 'AlwaysInstallElevated deaktivieren', 'FilterAdministratorToken aktivieren'],
    preserves: ['Anwendungsinstallation (mit UAC-Abfrage)', 'Admin-Funktionalität'],
    canUndo: true,
    undoPath: 'Registry → Policies\\System → UAC auf Standard zurücksetzen',
  },
  'kernel-file-integrity': {
    whatChecked: 'Kritische Kernel-Dateien (ntoskrnl.exe, hal.dll, ci.dll) auf gültige digitale Signaturen.',
    riskExplanation: 'Modifizierte Kernel-Dateien weisen auf ein Rootkit oder APT hin, das das OS auf tiefster Ebene kompromittiert hat.',
    passDetail: 'Alle kritischen Kernel-Dateien haben gültige Signaturen.',
    fixActionsTemplate: ['sfc /scannow ausführen', 'DISM /RestoreHealth ausführen', 'Vom Recovery-Medium reparieren'],
    preserves: ['Systemfunktionalität', 'Boot-Prozess'],
    canUndo: false,
  },
  'kernel-driver-paths': {
    whatChecked: 'Kernel-Treiber-Ladepfade — markiert Treiber aus Nicht-System-Verzeichnissen.',
    riskExplanation: 'Legitime Kernel-Treiber laden aus System32\\drivers. Treiber aus anderen Pfaden können bösartige Rootkits sein.',
    passDetail: 'Alle Kernel-Treiber aus Standard-Systempfaden geladen.',
    fixActionsTemplate: ['Nicht-System-Pfad-Treiber untersuchen', 'Verdächtige Treiber entfernen', 'Treibersignaturen verifizieren'],
    preserves: ['Legitime Treiber', 'Hardware-Funktionalität'],
    canUndo: false,
  },
};
