/**
 * SENTINEL — Deutsche Performance Scan-Check-Beschreibungen (15 Prüfungen)
 */
import type { CheckDetailTemplate } from './networkScanChecks';

export const PERFORMANCE_CHECK_DETAILS_DE: Record<string, CheckDetailTemplate> = {
  'dpc-latency': {
    whatChecked: 'Deferred Procedure Call (DPC) Latenz — misst Interrupt-Verarbeitungsverzögerung.',
    riskExplanation: 'Hohe DPC-Latenz verursacht Audio-Aussetzer, USB-Abbrüche und verzögerte Eingaben. Meist durch fehlerhafte Treiber verursacht.',
    passDetail: 'DPC-Latenz im akzeptablen Bereich (<500µs Durchschnitt).',
    fixActionsTemplate: ['Treiber mit hoher Latenz identifizieren', 'Problematische Treiber aktualisieren oder deaktivieren', 'Energiesparen auf USB-Controllern deaktivieren'],
    preserves: ['Audioqualität', 'USB-Geräte-Reaktionsfähigkeit'],
    canUndo: true,
    undoPath: 'Deaktivierte Treiber wieder aktivieren',
  },
  'timer-resolution': {
    whatChecked: 'System-Timer-Auflösung und Multimedia-Timer-Präzision.',
    riskExplanation: 'Standard-15,6ms-Timer-Auflösung verursacht Scheduling-Jitter. Anwendungen mit präzisem Timing-Bedarf laufen schlecht.',
    passDetail: 'Timer-Auflösung auf hohe Präzision gesetzt (1ms oder besser).',
    fixActionsTemplate: ['Globale Timer-Auflösung auf 1ms setzen', 'Multimedia-Timer-Dienst verifizieren'],
    preserves: ['Akkulaufzeit kann leicht sinken', 'Systemstabilität'],
    canUndo: true,
    undoPath: 'Timer-Auflösung auf Standard 15,6ms zurücksetzen',
  },
  'core-parking': {
    whatChecked: 'CPU-Core-Parking-Konfiguration und Energieplan-Kernauslastungs-Einstellungen.',
    riskExplanation: 'Aggressives Core-Parking deaktiviert CPU-Kerne zum Energiesparen und verursacht Stottern bei stoßweiser Belastung.',
    passDetail: 'Core-Parking für Reaktionsfähigkeit optimiert. Alle Kerne verfügbar.',
    fixActionsTemplate: ['Minimale Kerne auf 100% setzen', 'Energieplan für Leistung anpassen', 'Core-Parking über Registry deaktivieren'],
    preserves: ['Energieeffizienzmodus weiterhin verfügbar', 'Thermomanagement'],
    canUndo: true,
    undoPath: 'Energieplan → Ausgewogene Einstellungen wiederherstellen',
  },
  'memory-compression': {
    whatChecked: 'Windows-Speicherkomprimierung Status und Auswirkung auf Systemreaktionsfähigkeit.',
    riskExplanation: 'Speicherkomprimierung tauscht CPU-Zyklen gegen RAM-Kapazität. Bei ausreichend RAM verschwendet sie unnötig CPU.',
    passDetail: 'Speicherkomprimierung für verfügbaren RAM angemessen konfiguriert.',
    fixActionsTemplate: ['Speicherkomprimierung basierend auf RAM-Verfügbarkeit anpassen', 'Deaktivieren wenn RAM > 16GB'],
    preserves: ['Systemstabilität', 'Anwendungs-Speicherzugriff'],
    canUndo: true,
    undoPath: 'Enable-MMAgent -MemoryCompression',
  },
  'power-plan': {
    whatChecked: 'Aktiver Windows-Energieplan und Prozessor-Energieverwaltungseinstellungen.',
    riskExplanation: 'Ausgewogener/Energiespar-Plan drosselt die CPU-Frequenz und verursacht inkonsistente Leistung unter Last.',
    passDetail: 'Höchstleistungs- oder Ultimative-Leistungs-Energieplan aktiv.',
    fixActionsTemplate: ['Auf Höchstleistungsplan wechseln', 'Minimalen Prozessorstatus auf 100% setzen', 'Prozessor-Leerlauf deaktivieren'],
    preserves: ['Akkulaufzeit (reduziert bei Laptops)', 'Thermischer Spielraum'],
    canUndo: true,
    undoPath: 'Energieoptionen → Auf Ausgewogen wechseln',
  },
  'startup-impact': {
    whatChecked: 'Bootzeit, Anzahl der Startprogramme und deren kumulative Auswirkung.',
    riskExplanation: 'Zu viele Startprogramme verlangsamen die Bootzeit und verbrauchen Ressourcen, bevor der Benutzer interagieren kann.',
    passDetail: 'Startprogramme im akzeptablen Bereich. Bootzeit optimiert.',
    fixActionsTemplate: ['Nicht-essentielle Startprogramme deaktivieren', 'Start schwerer Anwendungen verzögern'],
    preserves: ['Essentielle Startanwendungen', 'Sicherheitssoftware-Autostart'],
    canUndo: true,
    undoPath: 'Task-Manager → Autostart → Programme wieder aktivieren',
  },
  'visual-effects': {
    whatChecked: 'Windows-Visuelleffekte-Einstellungen und deren GPU/CPU-Auswirkung.',
    riskExplanation: 'Übermäßige visuelle Effekte verschwenden GPU-Zyklen und erhöhen den Speicherverbrauch ohne funktionalen Nutzen.',
    passDetail: 'Visuelle Effekte für Leistung optimiert.',
    fixActionsTemplate: ['Visuelle Effekte auf „Für optimale Leistung anpassen" setzen', 'Nur essentielle Effekte beibehalten'],
    preserves: ['Desktop-Bedienbarkeit', 'Schriftglättung'],
    canUndo: true,
    undoPath: 'Systemeigenschaften → Erweitert → Visuelle Effekte → Optimale Darstellung',
  },
  'disk-queue': {
    whatChecked: 'Festplatten-E/A-Warteschlangentiefe, anstehende Operationen und Durchsatz-Engpässe.',
    riskExplanation: 'Hohe Festplatten-Warteschlangenlängen deuten auf Speicher-Engpass hin — Anwendungen warten auf E/A, was systemweite Verlangsamung verursacht.',
    passDetail: 'Festplatten-Warteschlangenlängen normal. Kein E/A-Engpass erkannt.',
    fixActionsTemplate: ['Prozesse mit hoher E/A identifizieren', 'Indizierungsdienst optimieren', 'SSD-Upgrade für HDD in Betracht ziehen'],
    preserves: ['Datenintegrität', 'Dateisystem-Operationen'],
    canUndo: false,
  },
  'pagefile-config': {
    whatChecked: 'Auslagerungsdatei-Konfiguration, Größe und Platzierung.',
    riskExplanation: 'Falsche Auslagerungsdatei-Konfiguration verursacht übermäßiges Paging, Anwendungsabstürze (Speichermangel) oder verschwendeten Speicherplatz.',
    passDetail: 'Auslagerungsdatei korrekt dimensioniert auf schnellstem Laufwerk.',
    fixActionsTemplate: ['Auslagerungsdatei auf 1,5x RAM-Größe setzen', 'Auf schnellste SSD platzieren', 'Auslagerungsdatei auf HDD deaktivieren'],
    preserves: ['Anwendungsstabilität', 'System-Speicherverwaltung'],
    canUndo: true,
    undoPath: 'Systemeigenschaften → Erweitert → Virtueller Arbeitsspeicher → Systemverwaltet',
  },
  'indexing-service': {
    whatChecked: 'Windows-Such-Indizierungsdienst Umfang und Ressourcenverbrauch.',
    riskExplanation: 'Breiter Indizierungsumfang verursacht ständige Hintergrund-Festplatten-E/A, besonders auf HDDs.',
    passDetail: 'Indizierung auf essentielle Orte beschränkt.',
    fixActionsTemplate: ['Indizierung auf Benutzerordner beschränken', 'Build- und Temp-Verzeichnisse ausschließen', 'Inhaltsindizierung auf SSDs deaktivieren'],
    preserves: ['Windows-Suchfunktionalität', 'Startmenü-Suche'],
    canUndo: true,
    undoPath: 'Indizierungsoptionen → Orte wieder hinzufügen',
  },
  'superfetch-prefetch': {
    whatChecked: 'SysMain (Superfetch) und Prefetch-Konfiguration für optimalen Anwendungsstart.',
    riskExplanation: 'Auf SSDs bietet Superfetch minimalen Nutzen bei Speicherverbrauch. Auf HDDs verbessert es die Startzeiten erheblich.',
    passDetail: 'SysMain entsprechend dem Speichertyp konfiguriert.',
    fixActionsTemplate: ['SysMain basierend auf primärem Speichertyp konfigurieren', 'Auf NVMe/SSD deaktivieren wenn RAM < 16GB'],
    preserves: ['Anwendungs-Startzeiten', 'Systemstabilität'],
    canUndo: true,
    undoPath: 'Dienste → SysMain → Automatisch',
  },
  'network-throttling': {
    whatChecked: 'Netzwerk-Drosselungsindex, Nagle-Algorithmus, TCP-Auto-Tuning und Empfangsfenstergröße.',
    riskExplanation: 'Standard-Netzwerkeinstellungen priorisieren Energiesparen über Durchsatz und reduzieren die Netzwerkleistung.',
    passDetail: 'Netzwerk-Drosselung deaktiviert. TCP-Auto-Tuning optimiert.',
    fixActionsTemplate: ['Netzwerk-Drosselungsindex deaktivieren', 'TCP-Auto-Tuning-Level optimieren', 'Nagle für niedrige Latenz deaktivieren'],
    preserves: ['Netzwerkstabilität', 'Verbindungszuverlässigkeit'],
    canUndo: true,
    undoPath: 'Registry → NetworkThrottlingIndex → Standard wiederherstellen',
  },
  'gpu-scheduling': {
    whatChecked: 'Hardware-beschleunigtes GPU-Scheduling (HAGS) Status und Treiberunterstützung.',
    riskExplanation: 'HAGS reduziert CPU-Overhead für GPU-Aufgabenplanung und verbessert Frametimes in Spielen und GPU-beschleunigten Workloads.',
    passDetail: 'Hardware-GPU-Scheduling aktiviert (falls unterstützt).',
    fixActionsTemplate: ['HAGS in Anzeigeeinstellungen aktivieren', 'GPU-Treiber aktualisieren'],
    preserves: ['Bildschirmausgabe', 'Anwendungskompatibilität'],
    canUndo: true,
    undoPath: 'Anzeigeeinstellungen → Grafik → HAGS deaktivieren',
  },
  'thread-affinity': {
    whatChecked: 'CPU-Topologie-Erkennung: physische Kerne, logische Threads, NUMA-Knoten und CCX/CCD-Layout.',
    riskExplanation: 'Falsche Thread-Planung über CCX/CCD-Grenzen (AMD) oder P/E-Kerne (Intel) verursacht Cache-Thrashing und Latenzspitzen.',
    passDetail: 'CPU-Topologie korrekt erkannt. Thread-Planung optimiert.',
    fixActionsTemplate: ['Bevorzugte Kerne konfigurieren', 'Prozess-Affinität für latenzsensitive Apps setzen'],
    preserves: ['Mehrkern-Workloads', 'Hintergrundverarbeitung'],
    canUndo: true,
    undoPath: 'Prozess-Affinität auf Standard zurücksetzen',
  },
  'game-mode': {
    whatChecked: 'Windows-Spielmodus, Game Bar und spielbezogene Optimierungseinstellungen.',
    riskExplanation: 'Der Spielmodus reduziert Hintergrundaktivität beim Spielen. Das Game-Bar-Overlay kann in einigen Spielen FPS-Einbrüche verursachen.',
    passDetail: 'Spielmodus konfiguriert. Game-Bar-Auswirkung minimiert.',
    fixActionsTemplate: ['Spielmodus aktivieren', 'Game Bar deaktivieren falls problematisch', 'Aufnahmen deaktivieren'],
    preserves: ['Spielfunktionalität', 'Streaming-Fähigkeit'],
    canUndo: true,
    undoPath: 'Windows-Einstellungen → Spiele → Standards wiederherstellen',
  },
  'disk-write-cache': {
    whatChecked: 'Festplatten-Schreibcache-Richtlinie auf dem primären Speichergerät (SSD/HDD).',
    riskExplanation: 'Deaktivierter Schreibcache auf HDDs reduziert die Schreibleistung erheblich. Stromausfall mit aktiviertem Schreibcache kann auf HDDs ohne USV zu Datenverlust führen.',
    passDetail: 'Festplatten-Schreibcache aktiviert oder SSD/NVMe erkannt (Cache weniger kritisch).',
    fixActionsTemplate: ['Festplatten-Schreibcache auf primärem Laufwerk aktivieren', 'USV/Batteriebackup für Datensicherheit verifizieren'],
    preserves: ['Datenintegrität (USV sicherstellen bei HDD)', 'Leseleistung unverändert'],
    canUndo: true,
    undoPath: 'Geräte-Manager → Laufwerke → Eigenschaften → Richtlinien → Schreibcache deaktivieren',
  },
  'cpu-topology': {
    whatChecked: 'CPU-Kern- und Thread-Topologie — physische Kerne, logische Threads, SMT/HT-Status.',
    riskExplanation: 'Fehlerhafte Kernerkennung kann zu suboptimaler Thread-Verteilung und reduzierter Leistung bei Multi-Thread-Anwendungen führen.',
    passDetail: 'CPU-Topologie korrekt erkannt. Alle Kerne und Threads aktiv.',
    fixActionsTemplate: ['SMT/HT im BIOS aktivieren', 'Auf deaktivierte Kerne prüfen'],
    preserves: ['CPU-Funktionalität', 'Systemstabilität'],
    canUndo: false,
  },
  'interrupt-steering': {
    whatChecked: 'Interrupt-Affinität und RSS-Verteilung (Receive Side Scaling) über CPU-Kerne.',
    riskExplanation: 'Schlechte Interrupt-Verteilung konzentriert alle Netzwerk-/USB-Interrupts auf einen Kern — Latenzspitzen und Paketverluste.',
    passDetail: 'Interrupts über mehrere Kerne verteilt.',
    fixActionsTemplate: ['RSS auf Netzwerkadaptern aktivieren', 'Interrupt-Affinität über Geräte-Manager konfigurieren'],
    preserves: ['Netzwerkdurchsatz', 'Gerätefunktionalität'],
    canUndo: true,
    undoPath: 'RSS-Einstellungen des Netzwerkadapters auf Standard zurücksetzen',
  },
  'large-pages': {
    whatChecked: 'Large-Pages-Unterstützung (2MB) und SeLockMemoryPrivilege-Zuweisung.',
    riskExplanation: 'Large Pages reduzieren TLB-Misses für speicherintensive Anwendungen — 5-30% Leistungssteigerung für Datenbanken und VMs.',
    passDetail: 'Large Pages unterstützt. SeLockMemoryPrivilege zugewiesen.',
    fixActionsTemplate: ['SeLockMemoryPrivilege dem Benutzer gewähren', 'Anwendungen für Large Pages neu starten'],
    preserves: ['Systemspeicherverwaltung', 'Anwendungskompatibilität'],
    canUndo: true,
    undoPath: 'SeLockMemoryPrivilege vom Benutzerkonto entfernen',
  },
  'vram-status': {
    whatChecked: 'GPU-Modell, VRAM-Kapazität und Treiberversion.',
    riskExplanation: 'Unzureichender VRAM verursacht Textur-Streaming-Ruckler und GPU-Speicher-Paging mit gravierenden Auswirkungen auf die Grafikleistung.',
    passDetail: 'GPU mit ausreichendem VRAM erkannt.',
    fixActionsTemplate: ['GPU-Treiber aktualisieren', 'Texturqualität reduzieren bei begrenztem VRAM'],
    preserves: ['Bildschirmausgabe', 'Aktuelle Auflösungseinstellungen'],
    canUndo: false,
  },
  'standby-list': {
    whatChecked: 'Verfügbarer physischer RAM und Standby-Listen-Druck.',
    riskExplanation: 'Wenn freier RAM unter 5% fällt, lagert Windows aggressiv auf Festplatte aus — systemweites Ruckeln und Anwendungs-Hänger.',
    passDetail: 'Ausreichend freier RAM verfügbar. Standby-Liste gesund.',
    fixActionsTemplate: ['Speicherintensive Anwendungen schließen', 'Standby-Liste leeren', 'Auslagerungsdatei vergrößern'],
    preserves: ['Laufende Anwendungen', 'Systemstabilität'],
    canUndo: false,
  },
  'io-priority': {
    whatChecked: 'Hintergrund-I/O-Aktivität von Windows Update und BITS-Diensten.',
    riskExplanation: 'Aktive Windows-Update-Downloads verbrauchen Festplatten-I/O-Bandbreite — Verzögerungen für Benutzeranwendungen, besonders auf HDDs.',
    passDetail: 'Hintergrund-I/O-Dienste im Leerlauf. Keine Festplatten-Bandbreiten-Konkurrenz.',
    fixActionsTemplate: ['Windows-Update-Downloads pausieren', 'BITS auf niedrige Priorität setzen', 'Updates für Nebenzeiten planen'],
    preserves: ['Update-Funktionalität', 'System-Sicherheitspatches'],
    canUndo: true,
    undoPath: 'Windows-Update-Dienste fortsetzen',
  },
  'ntfs-health': {
    whatChecked: 'NTFS-Volume-Gesundheit, MFT-Fragmentierung und freier Speicherplatz auf Systemlaufwerk.',
    riskExplanation: 'Ein degradiertes NTFS-Volume mit wenig freiem Speicher verursacht exponentiell langsamere Dateioperationen und riskiert Datenbeschädigung.',
    passDetail: 'NTFS-Volume gesund. Ausreichend freier Speicherplatz.',
    fixActionsTemplate: ['chkdsk /scan ausführen', 'Speicherplatz freigeben', 'MFT defragmentieren (nur HDD)'],
    preserves: ['Dateisystem-Integrität', 'Gespeicherte Daten'],
    canUndo: false,
  },
  'winsxs-store': {
    whatChecked: 'Windows Component Store (WinSxS) Größe und Bereinigungspotenzial.',
    riskExplanation: 'Ein übergroßer WinSxS-Ordner (>15GB) verschwendet Speicherplatz und kann Wartungsoperationen wie Windows Update verlangsamen.',
    passDetail: 'WinSxS Component Store in akzeptabler Größe.',
    fixActionsTemplate: ['DISM /StartComponentCleanup ausführen', 'Ersetzte Updates entfernen', 'Temporäre Dateien bereinigen'],
    preserves: ['Installierte Komponenten', 'Rollback-Fähigkeit (für aktuelle Updates)'],
    canUndo: false,
  },
  'registry-size': {
    whatChecked: 'Registry-Hive-Größen (HKLM + HKCU) und Schlüsselanzahl.',
    riskExplanation: 'Eine aufgeblähte Registry mit Tausenden verwaisten Schlüsseln verlangsamt Bootzeit, Anmeldung und Anwendungsstart.',
    passDetail: 'Registry-Größe im normalen Bereich.',
    fixActionsTemplate: ['Verwaiste Registry-Schlüssel bereinigen', 'Übriggebliebene Deinstallationseinträge entfernen'],
    preserves: ['Installierte Software-Einstellungen', 'Systemkonfiguration'],
    canUndo: false,
  },
  'context-switches': {
    whatChecked: 'CPU-Kontextwechselrate — misst Thread-Scheduling-Overhead.',
    riskExplanation: 'Extrem hohe Kontextwechselraten (>100k/s) deuten auf Thread-Konkurrenz hin — CPU-Overhead und reduzierter Anwendungsdurchsatz.',
    passDetail: 'Kontextwechselrate im normalen Bereich.',
    fixActionsTemplate: ['Prozesse mit hoher Thread-Anzahl identifizieren', 'Unnötige Hintergrunddienste reduzieren'],
    preserves: ['Laufende Anwendungen', 'Systemreaktionsfähigkeit'],
    canUndo: false,
  },
  'ram-stability': {
    whatChecked: 'RAM-Kapazität, Geschwindigkeit, Dual-Channel-Status und Hardware-Fehlerhistorie.',
    riskExplanation: 'Fehlerhafter oder nicht-übereinstimmender RAM verursacht Bluescreens, Datenbeschädigung und intermittierende Abstürze.',
    passDetail: 'RAM-Konfiguration gesund. Keine Hardware-Fehler erkannt.',
    fixActionsTemplate: ['Windows-Speicherdiagnose ausführen', 'Auf nicht-übereinstimmende RAM-Module prüfen', 'XMP/DOCP-Profil verifizieren'],
    preserves: ['Systemstabilität', 'Gespeicherte Daten'],
    canUndo: false,
  },
  'thermal-status': {
    whatChecked: 'CPU- und System-Thermalzonen-Temperaturen und kritische Schwellenwerte.',
    riskExplanation: 'Hohe Temperaturen verursachen thermisches Throttling (reduzierte CPU-Geschwindigkeit), verkürzte Hardware-Lebensdauer und potenzielle Systemabschaltungen.',
    passDetail: 'Temperaturen im sicheren Betriebsbereich.',
    fixActionsTemplate: ['CPU-Kühler und Gehäuselüfter reinigen', 'Wärmeleitpaste erneuern', 'Gehäusebelüftung verbessern'],
    preserves: ['Hardware-Langlebigkeit', 'Systemleistung'],
    canUndo: false,
  },
};
