/**
 * SENTINEL — Privacy Scan Check Detail Definitions (22 checks)
 * Each check defines its detail template. Runtime data fills in the blanks.
 */

import type { CheckDetailTemplate } from './networkScanChecks';

export const PRIVACY_CHECK_DETAILS: Record<string, CheckDetailTemplate> = {
  'hardware-id-exposure': {
    whatChecked: 'Windows Hardware ID (UUID) accessibility to applications and websites.',
    riskExplanation: 'Hardware IDs uniquely identify your machine. If exposed, trackers can fingerprint you across browser sessions, VPNs, and account changes.',
    passDetail: 'Hardware ID access restricted.',
    fixActionsTemplate: ['Restrict WMIC access to admin only', 'Block Hardware ID queries from non-admin processes'],
    preserves: ['System functionality', 'Driver installations'],
    canUndo: true,
    undoPath: 'Settings → Privacy → Restore Hardware ID access',
  },
  'advertising-id': {
    whatChecked: 'Windows Advertising ID status (used by Microsoft and third-party apps for ad targeting).',
    riskExplanation: 'The advertising ID lets apps and advertisers track your behavior across all Microsoft Store apps.',
    passDetail: 'Advertising ID disabled.',
    fixActionsTemplate: ['Disable advertising ID via registry', 'Reset advertising ID'],
    preserves: ['App functionality', 'Microsoft Store access'],
    canUndo: true,
    undoPath: 'Windows Settings → Privacy → Advertising ID → On',
  },
  'telemetry-registry': {
    whatChecked: 'Windows telemetry level, DiagTrack service, and Connected User Experiences service.',
    riskExplanation: 'Full telemetry sends detailed usage data, app crash dumps, and browsing data to Microsoft. Even "Required" level sends significant data.',
    passDetail: 'Telemetry set to minimum. DiagTrack service restricted.',
    fixActionsTemplate: ['Set telemetry to Required (0)', 'Disable DiagTrack service', 'Block telemetry endpoints in hosts file'],
    preserves: ['Windows Update functionality', 'Microsoft Defender updates'],
    canUndo: true,
    undoPath: 'Windows Settings → Privacy → Diagnostics → Full',
  },
  'webcam-mic-lock': {
    whatChecked: 'Camera and microphone access permissions, which apps have access, and notification settings.',
    riskExplanation: 'Unrestricted webcam/mic access allows spyware to record audio/video without visible indicators.',
    passDetail: 'Camera and mic require per-app consent. Access notifications enabled.',
    fixActionsTemplate: ['Disable global camera access', 'Disable global mic access', 'Enable access notifications'],
    preserves: ['Camera/mic work when you explicitly allow'],
    canUndo: true,
    undoPath: 'Windows Settings → Privacy → Camera/Microphone → On',
  },
  'clipboard-history': {
    whatChecked: 'Clipboard history feature, clipboard sync across devices, and clipboard data retention.',
    riskExplanation: 'Clipboard history stores everything you copy — passwords, sensitive text, private data — and may sync to the cloud.',
    passDetail: 'Clipboard history disabled. Cloud sync off.',
    fixActionsTemplate: ['Disable clipboard history', 'Disable clipboard cloud sync', 'Clear clipboard data'],
    preserves: ['Normal copy/paste still works', 'Just no history retention'],
    canUndo: true,
    undoPath: 'Windows Settings → System → Clipboard → History On',
  },
  'metadata-stripper': {
    whatChecked: 'Whether Sentinel metadata stripping is available for files shared externally.',
    riskExplanation: 'Photos and documents contain hidden metadata: GPS location, device info, author name, edit history. Sharing without stripping leaks personal data.',
    passDetail: 'Metadata stripping available via Vault.',
    fixActionsTemplate: ['Enable automatic metadata stripping for uploads'],
    preserves: ['Original files untouched', 'Stripped copies created'],
    canUndo: false,
  },
  'cortana-web-search': {
    whatChecked: 'Cortana status, web search from Start menu, and Bing integration in Windows Search.',
    riskExplanation: 'Start menu web search sends every search query to Microsoft/Bing, including typos and sensitive searches.',
    passDetail: 'Cortana disabled. Web search from Start menu disabled.',
    fixActionsTemplate: ['Disable Cortana via registry', 'Disable BingSearchEnabled', 'Disable web results in Start menu'],
    preserves: ['Local file search still works', 'Settings search works'],
    canUndo: true,
    undoPath: 'Registry → Search → BingSearchEnabled=1',
  },
  'error-reporting': {
    whatChecked: 'Windows Error Reporting (WER) service and crash dump upload settings.',
    riskExplanation: 'Error reports can contain memory dumps with passwords, session tokens, and private data. These are uploaded to Microsoft.',
    passDetail: 'WER service stopped. Crash dumps kept locally only.',
    fixActionsTemplate: ['Stop WerSvc service', 'Set WER to local-only mode', 'Disable automatic crash dump uploads'],
    preserves: ['Local crash dumps still generated for debugging'],
    canUndo: true,
    undoPath: 'Services → WerSvc → Automatic',
  },
  'wifi-sense': {
    whatChecked: 'WiFi Sense, automatic hotspot connection, and open network sharing.',
    riskExplanation: 'WiFi Sense shares your WiFi passwords with contacts and auto-connects to open networks — both major security risks.',
    passDetail: 'WiFi Sense disabled. Auto-connect to open networks off.',
    fixActionsTemplate: ['Disable WiFi Sense', 'Disable auto-connect to suggested open hotspots'],
    preserves: ['Manual WiFi connections work normally'],
    canUndo: true,
    undoPath: 'Network Settings → WiFi → Advanced → Enable WiFi Sense',
  },
  'bluetooth-status': {
    whatChecked: 'Bluetooth adapter status, discoverability, and pairing mode.',
    riskExplanation: 'Always-on Bluetooth in discoverable mode allows nearby attackers to probe your device, attempt pairing, and exploit BT vulnerabilities.',
    passDetail: 'Bluetooth running but not in discoverable mode.',
    fixActionsTemplate: ['Disable Bluetooth when not in use', 'Set to non-discoverable'],
    preserves: ['Paired devices continue working'],
    canUndo: true,
    undoPath: 'Bluetooth Settings → Turn on / Set discoverable',
  },
  'gpo-hardening': {
    whatChecked: 'Group Policy Object settings for security: audit policies, account lockout, screen lock.',
    riskExplanation: 'Without hardened GPOs, account lockout is missing (brute force works forever), audit logging is disabled, and autorun is enabled.',
    passDetail: 'GPO hardening applied. Audit policies active. Autorun disabled.',
    fixActionsTemplate: ['Apply CIS Benchmark Level 1 GPO settings', 'Enable audit policies', 'Disable autorun for all drives'],
    preserves: ['User experience mostly unchanged', 'Software installations still work'],
    canUndo: true,
    undoPath: 'Group Policy Editor → Reset to defaults',
  },
  'uac-stealth-mode': {
    whatChecked: 'UAC (User Account Control) level, consent prompt behavior, and admin approval mode.',
    riskExplanation: 'UAC below maximum allows programs to silently elevate to admin without your knowledge. This is the #1 privilege escalation vector.',
    passDetail: 'UAC at maximum level. Always notify on changes.',
    fixActionsTemplate: ['Set ConsentPromptBehaviorAdmin=2 (always prompt)', 'Set PromptOnSecureDesktop=1', 'Enable admin approval mode'],
    preserves: ['You will see more UAC prompts — this is the intended security behavior'],
    canUndo: true,
    undoPath: 'UAC Settings → Drag slider to lower level',
  },
  'anti-keylogging': {
    whatChecked: 'Windows typing data collection, inking recognition, and keyboard telemetry.',
    riskExplanation: 'Windows collects typing patterns for personalization, which effectively logs your keystrokes and sends them to Microsoft.',
    passDetail: 'Typing data collection disabled. Inking recognition off.',
    fixActionsTemplate: ['Disable "Getting to know me" typing data', 'Disable inking recognition', 'Clear typing history'],
    preserves: ['Keyboard works normally', 'Autocorrect still functions'],
    canUndo: true,
    undoPath: 'Settings → Privacy → Inking & Typing → On',
  },
  'tracking-protection': {
    whatChecked: 'Windows activity history, timeline, and cross-device activity sync.',
    riskExplanation: 'Activity tracking records every app you open, every file you edit, and every website you visit — synced across your Microsoft account.',
    passDetail: 'Activity history disabled. Timeline cleared.',
    fixActionsTemplate: ['Disable activity history collection', 'Disable cross-device sync', 'Clear activity history'],
    preserves: ['App functionality unchanged', 'Just no tracking'],
    canUndo: true,
    undoPath: 'Settings → Privacy → Activity History → On',
  },
  'military-shredder': {
    whatChecked: 'Whether Sentinel secure file deletion (DoD 5220.22-M compliant) is available.',
    riskExplanation: 'Normal file deletion leaves recoverable data on disk. Forensic tools can recover "deleted" files, passwords, and private documents.',
    passDetail: 'Sentinel Military Shredder available via Vault.',
    fixActionsTemplate: [],
    preserves: [],
    canUndo: false,
  },
  'dns-leak-protection': {
    whatChecked: 'Whether DNS queries are routed through VPN tunnel when VPN is active.',
    riskExplanation: 'DNS leaks expose every website you visit to your ISP, even when VPN is active. This completely undermines VPN privacy.',
    passDetail: 'DNS routed through VPN provider DNS servers.',
    fixActionsTemplate: ['Set DNS to VPN-only servers', 'Flush DNS cache', 'Block non-VPN DNS in firewall'],
    preserves: ['VPN connection unchanged', 'Internet access maintained'],
    canUndo: true,
    undoPath: 'DNS & Privacy → DNS Configuration → Restore',
  },
  'location-services': {
    whatChecked: 'Windows Location service, per-app location access, and location history.',
    riskExplanation: 'Location services share your physical position with apps and Microsoft. Location history creates a timeline of your movements.',
    passDetail: 'Location services disabled.',
    fixActionsTemplate: ['Disable location service', 'Clear location history', 'Disable per-app location access'],
    preserves: ['Weather app may need manual location', 'Maps need manual entry'],
    canUndo: true,
    undoPath: 'Settings → Privacy → Location → On',
  },
  'usb-storage': {
    whatChecked: 'USB mass storage device policy, autorun settings, and device history.',
    riskExplanation: 'Unrestricted USB allows anyone to plug in a drive and exfiltrate data, install malware, or execute autorun payloads.',
    passDetail: 'USB storage restricted. Autorun disabled.',
    fixActionsTemplate: ['Set USB storage to read-only or disabled', 'Disable autorun for removable drives', 'Enable USB device logging'],
    preserves: ['USB keyboards and mice still work', 'Only storage devices affected'],
    canUndo: true,
    undoPath: 'Group Policy → Removable Storage Access → Allow',
  },
  'lockscreen-hardening': {
    whatChecked: 'Lock screen timeout, password/PIN requirement, and lock screen information display.',
    riskExplanation: 'Without auto-lock, leaving your machine unattended gives full access. Lock screen info can leak notifications and personal data.',
    passDetail: 'Auto-lock enabled. Lock screen notifications restricted.',
    fixActionsTemplate: ['Set auto-lock to 5 minutes', 'Disable lock screen notifications', 'Require PIN/password on wake'],
    preserves: ['Lock screen clock and date', 'Emergency notifications'],
    canUndo: true,
    undoPath: 'Settings → Lock Screen → Customize',
  },
  'winget-available': {
    whatChecked: 'Whether Windows Package Manager (winget) is installed and up to date.',
    riskExplanation: 'Winget provides verified software installations. Without it, users may download software from unverified sources.',
    passDetail: 'Winget installed and functional.',
    fixActionsTemplate: ['Install winget from Microsoft Store'],
    preserves: ['Existing installed software unchanged'],
    canUndo: false,
  },
  'shell-extension-audit': {
    whatChecked: 'Third-party shell extensions loaded into Explorer, potential DLL injection vectors.',
    riskExplanation: 'Malicious shell extensions run code inside Explorer with your permissions. They can keylog, screenshot, and modify files.',
    passDetail: 'All shell extensions from approved publishers.',
    fixActionsTemplate: ['Review and disable untrusted shell extensions', 'Block unsigned extensions'],
    preserves: ['Windows Explorer functionality', 'Approved extensions continue working'],
    canUndo: true,
    undoPath: 'Registry → ShellExtensions → Re-enable',
  },
  'data-science-dashboard': {
    whatChecked: 'Whether Sentinel data analytics and trend visualization is integrated.',
    riskExplanation: 'Without trend data, you cannot see patterns in security events over time — recurring threats go unnoticed.',
    passDetail: 'Data Science Dashboard integrated into Sentinel.',
    fixActionsTemplate: [],
    preserves: [],
    canUndo: false,
  },
};
